### DISCUSSION TITLE
Some help with this regex?

### DISCUSSION THREAD

**Discussion by davidcbbc** [aquasecurity/trivy#2109] [Q&A] [answered]
Hello 👋

So , I've been currently exploring trivy and wanted to use it to detect secrets within a Jenkins pipeline.
Although it returns some keys, it doesn't return them all.
So , I thought in adding this regex that I found 
`(?i)((access_key|access_token|admin_pass|admin_user|algolia_admin_key|algolia_api_key|alias_pass|alicloud_access_key|amazon_secret_access_key|amazonaws|ansible_vault_password|aos_key|api_key|api_key_secret|api_key_sid|api_secret|api.googlemaps AIza|apidocs|apikey|apiSecret|app_debug|app_id|app_key|app_log_level|app_secret|appkey|appkeysecret|application_key|appsecret|appspot|auth_token|authorizationToken|authsecret|aws_access|aws_access_key_id|aws_bucket|aws_key|aws_secret|aws_secret_key|aws_token|AWSSecretKey|b2_app_key|bashrc password|bintray_apikey|bintray_gpg_password|bintray_key|bintraykey|bluemix_api_key|bluemix_pass|browserstack_access_key|bucket_password|bucketeer_aws_access_key_id|bucketeer_aws_secret_access_key|built_branch_deploy_key|bx_password|cache_driver|cache_s3_secret_key|cattle_access_key|cattle_secret_key|certificate_password|ci_deploy_password|client_secret|client_zpk_secret_key|clojars_password|cloud_api_key|cloud_watch_aws_access_key|cloudant_password|cloudflare_api_key|cloudflare_auth_key|cloudinary_api_secret|cloudinary_name|codecov_token|config|conn.login|connectionstring|consumer_key|consumer_secret|credentials|cypress_record_key|database_password|database_schema_test|datadog_api_key|datadog_app_key|db_password|db_server|db_username|dbpasswd|dbpassword|dbuser|deploy_password|digitalocean_ssh_key_body|digitalocean_ssh_key_ids|docker_hub_password|docker_key|docker_pass|docker_passwd|docker_password|dockerhub_password|dockerhubpassword|dot-files|dotfiles|droplet_travis_password|dynamoaccesskeyid|dynamosecretaccesskey|elastica_host|elastica_port|elasticsearch_password|encryption_key|encryption_password|env.heroku_api_key|env.sonatype_password|eureka.awssecretkey)[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['\"]([0-9a-zA-Z\-_=]{8,64})['\"]`

And the problem here is that I can't make it to work within a **trivy-secret.yaml** file . I've been having my head around this for several days now and I appreciate if someone could help me.

Peace ✌️

**Comment by davidcbbc** [comment]
Also , I tried to test with a simple file that have "password=asd" in it with the following **trivy-secret.yaml** : 

```
rules:
  - id: rule1
    category: general
    title: Generic Rule
    severity: HIGH
    keywords:
      - password
    regex: (?i)(?P<key>(secret))(=|:).{0,5}['"](?P<secret>[0-9a-zA-Z\-_=]{8,64})['"]
    secret-group-name: secret

```

Still no results from it ... what am I doing wrong?

**Comment by amaurybsouza** [comment]
Could you update us around this, maybe I can help you on this issue.

**Comment by ankitcybersolutions** [comment, marked as answer]
Hello Trivy Team - Could you please update on this?
I need example of trivy-secret.yaml which can fetch all types of secrets. For example -

**Reply by knqyf263** [reply]
Do you mean those passwords should be detected by the following rule @davidcbbc shared?

```
rules:
  - id: rule1
    category: general
    title: Generic Rule
    severity: HIGH
    keywords:
      - password
    regex: (?i)(?P<key>(secret))(=|:).{0,5}['"](?P<secret>[0-9a-zA-Z\-_=]{8,64})['"]
    secret-group-name: secret
```

**Reply by ankitcybersolutions** [reply]
yes @knqyf263 - Thanks for your response. Please **share generic rule configuration to detect all types of passwords within our source code**? WIth in-built-in rules, we are not expecting complete result. Sample examples below -

Also, please **share complete docker command to scan secret in source repository** with --secret-config  trivy-secret.yaml ( only fetch secrets ).

**Reply by knqyf263** [reply]
We don't want to add a generic rule as it brings a log of false positives, but the custom rule should work.
@afdesk Would you take a look?

**Reply by ankitcybersolutions** [reply]
Yes @knqyf263 , please help me to create custom rule to detect all sort of passwords. Kindly share trivy-secret.yaml so that I will test it against my source code.
Also, please share complete docker command to scan secret in source repository with --secret-config trivy-secret.yaml ( only fetch secrets ).

**Reply by ankitcybersolutions** [reply]
Good Morning @knqyf263 , Could you please share your response here?

**Reply by knqyf263** [reply]
I asked @afdesk. Please be patient.

**Reply by afdesk** [reply]
@ankitcybersolutions i'll take a look in a few hours.

**Reply by ankitcybersolutions** [reply]
Hello @afdesk  - Sure, i will wait for your response here.

**Reply by afdesk** [reply]
@ankitcybersolutions 
I've created `trivy-secret.yaml` for your case:
```yaml
rules:
  - id: rule1
    category: general
    title: Generic Rule
    severity: HIGH
    keywords:
     - password
    secret-group-name: secret
    regex: (?i)(?P<key>(password))[0-9]?(=|:).{0,5}['"]?(?P<secret>[0-9a-zA-Z\-_=]{8,64})['"]?
```
result:
```sh
$ trivy fs --scanners secret .
2023-03-07T19:13:57.174+0600	INFO	Secret scanning is enabled
2023-03-07T19:13:57.174+0600	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-07T19:13:57.174+0600	INFO	Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection
2023-03-07T19:13:57.174+0600	INFO	Loading trivy-secret.yaml for secret scanning...

passsww (secrets)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 2, CRITICAL: 0)

HIGH: general (rule1)
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Generic Rule
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 passsww:1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 [ password1=D7********
   2   password2=4WPB4***********
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


HIGH: general (rule1)
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Generic Rule
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 passsww:2
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   password1=D7********
   2 [ password2=4WPB4***********
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```
