### DISCUSSION TITLE
developing a python plugin for local use of trivy without github

### DISCUSSION THREAD

**Discussion by MIO1100** [aquasecurity/trivy#3715] [Q&A] [answered]
Hello, I recently ran into the problem of developing a plugin for trivy. I need to locally install a plugin that is written in python, and I need to process the scan result. I used this config.
```
name: "changer"
version: "0.1.0"
usage: trivy changer -- --image-name <image-name>
description: |-
  A Trivy plugin
platforms:
    bin: ./script.py
    uri: ./script.py
```

If I run the command:
`trivy plugin install plugin.yaml -d ` then I get a variety of errors:
For example:
FATAL   plugin install error:
    github.com/aquasecurity/trivy/pkg/commands.NewPluginCommand.func1
        /home/runner/work/trivy/trivy/pkg/commands/app.go:623
  - failed to load the plugin metadata:
    github.com/aquasecurity/trivy/pkg/plugin.Install
        /home/runner/work/trivy/trivy/pkg/plugin/plugin.go:161
  - file open error:
    github.com/aquasecurity/trivy/pkg/plugin.loadMetadata
        /home/runner/work/trivy/trivy/pkg/plugin/plugin.go:305
  - open /tmp/trivy-plugin1395973207/plugin.yaml: no such file or directory

Maybe I'm doing something wrong? The script doesn't even start executing. If you use a Bash script, the error repeats. 
Please, write an algorithm for the local use of plugins without github. Thanks
