### DISCUSSION TITLE
Github Actions failure with unable to initialize scanner

### DISCUSSION THREAD

**Discussion by anupx73** [aquasecurity/trivy#4356] [Q&A] [answered]
### Question

I am using a very basic Trivy scanning on a docker image as part of the github action workflow. Few weeks back I tested my workflow with same code but now its throwing the following error:

`FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: failed to parse the image name: could not parse reference: $IMAGE_NAME:$IMAGE_TAG`

After several hours of trial and error I could not fix and unable to spot any changes in my repo which can cause this. Here is my code for building docker image and scanning it with trivy action.

```
  # Build Container Image
  - name: Image build
    run: |
      docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG

  # Trivy Scan for Container Image Vulnarability
  - name: Trivy Image Scanning for Vulnarability
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: '$IMAGE_NAME:$IMAGE_TAG'
      format: 'sarif'
      output: 'trivy-results.sarif'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'
```

### Target

Container Image

### Scanner

Vulnerability

### Output Format

SARIF

### Mode

Standalone

### Operating System

Ubuntu
