### DISCUSSION TITLE
Request to support defsec policy settings similar to cloudsploit plugin settings

### DISCUSSION THREAD

**Discussion by AkhtarAmir** [aquasecurity/trivy#4357] [Ideas]
### Description

In cloussploit, we have an options to give settings for some plugins like desirec encyrption level for SNS or desired instance types for RDS. We want to have something similar to pass on to defsec policies and produce results based on those user given input.

### Target

AWS

### Scanner

Misconfiguration

**Comment by knqyf263** [comment]
@giorod3 How can we allow users to pass settings? (cc: @itaysk)

**Reply by AkhtarAmir** [reply]
@knqyf263 the idea is to make these settings a part of cloud config that we already have. I discussed this with Simar and he said that we can create another key under each cloud for settings as below:

```
cloud:
  # whether to force a cache update for every scan
  update-cache: false

  # how old cached results can be before being invalidated
  max-cache-age: 24h

  # aws-specific cloud settings
  aws:
    # the user given settings for aws policies
    policy-settings:
      AVD-AWS-0050:
        aws_dynamo_desired_encryption: "awskms"
        aws_kms_desired_encryptiion: "awscmk"
      AVD-AWS-0051:
        aws_dynamo_desired_encryption: "awskms"

    # the aws region to use
    region: us-east-1

    # the aws endpoint to use (not required for general use)
    endpoint: https://my.custom.aws.endpoint

    # the aws account to use (this will be determined from your environment when not set)
    account: 123456789012
```
<img width="711" alt="Screenshot 2023-05-15 at 3 16 37 PM" src="https://github.com/aquasecurity/trivy/assets/31914988/7355d425-57be-447d-b803-86574f955fa1">
