### DISCUSSION TITLE
Support workspace.members parsing for Cargo.toml analysis

### DISCUSSION THREAD

**Discussion by anfedotoff** [aquasecurity/trivy#5278] [Development]
### Description

Hi :wave: !
Thanks for such awesome project!
I'll try to add  workflow with **trivy** as vulnerability scanner for our Rust [project](https://github.com/ispras/casr/pull/155), but I faced some problems.
`Cargo.toml` of our project looks like this:

```toml
[workspace.package]
version = "2.8.1"

[workspace]
members = ["casr", "libcasr"]
```
It doesn't have any dependencies in workspace, all dependencies are located in members. It seems to me, that it is possible to parse `members` section and then parse appropriate Cargo.toml configs to extract dependencies.
I have already tried, it works for me. I can open PR:).

### Target

Filesystem

### Scanner

Vulnerability
