### DISCUSSION TITLE
Scanning for secrets in ansible `host_vars/group_vars`

### DISCUSSION THREAD

**Discussion by nodiscc** [aquasecurity/trivy#6097] [Ideas]
### Description

Moved from https://github.com/aquasecurity/trivy/issues/2213

I want to scan `host_vars/group_vars` directories for passwords, as these are the only places in my projects where config variables can be stored (I keep them out of the inventory/playbook files)

I created this simple `trivy-secret.yaml`

```yaml
rules:
  - id: ansible-passwords
    category: general
    title: Passwords in ansible host/group vars
    severity: HIGH
    keywords:
      - password
    regex: (?P<key>(password):) +['"]?(?P<secret>[0-9a-zA-Z\-_=;,!]{4,64})['"]?
    allow-rules:
      - id: vaulted-variable
        description: skip variables encrypted with ansible-vault
        regex: '!vault'
```

Limitations:
 - this only detects variables named `*password` (covers 99% of my use case, but there may be other variables named `*secret_key`, etc)
 - the `allow-rule` is to exclude inline vault-encrypted string in plaintext files [[1]](https://docs.ansible.com/ansible/latest/cli/ansible-vault.html#encrypt-string) (example below), it should exclude values *starting* with `!vault |` but currently excludes everything _containing_ this string (could not find a working regex to detect the beginning of values)
 - You have to run trivy twice (once for `host_vars`, once for `group_vars` - when I ran it on the full project it started scanning other, large directories such as `.venv`, `ansible_collections`, etc. which are out of scope, and I couldn't find a way to show what was being scanned/how to exclude these with `--skip-dirs`)
 - the regex for `secret` might not be exhaustive (some characters prevent detection, see example below)
 - there may be some false positives on comments such as `# password: CHANGEME`, etc
 - the variable name itself is redacted with `*****` (I would expect it to only redact the value)

```yaml
$ head -n 10 playbooks/default/host_vars/my.example.org/my.example.org.yml
my_app_password: P455W0RD
my_app2_password: "P455W0RD"
my_app00_password: pa!vaultssword
my_app3_password: 'P455W0RD'
my_app4_password: <P455W0R<D
msmtp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          333464636264343265...
```

```bash
$ trivy fs --scanners secret /path/to/ansible/project/host_vars/
2024-02-10T16:21:06.916+0100	INFO	Secret scanning is enabled
2024-02-10T16:21:06.916+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-02-10T16:21:06.916+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.48/docs/scanner/secret/#recommendation for faster secret detection
2024-02-10T16:21:06.916+0100	INFO	Loading trivy-secret.yaml for secret scanning...

my.example.org/my.example.org.yml (secrets)

Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 3, CRITICAL: 0)

HIGH: general (ansible-passwords)
══════════════════════════════════════════════════════════════════════════════════════════
Passwords in ansible host/group vars
──────────────────────────────────────────────────────────────────────────────────────────
 my.example.org/my.example.org.yml:1
──────────────────────────────────────────────────────────────────────────────────────────
   1 [ my_app_******************
   2   my_app2_********************
──────────────────────────────────────────────────────────────────────────────────────────


HIGH: general (ansible-passwords)
══════════════════════════════════════════════════════════════════════════════════════════
Passwords in ansible host/group vars
──────────────────────────────────────────────────────────────────────────────────────────
 my.example.org/my.example.org.yml:2
──────────────────────────────────────────────────────────────────────────────────────────
   1   my_app_******************
   2 [ my_app2_********************
   3   my_app00_password: pa!vaultssword
──────────────────────────────────────────────────────────────────────────────────────────


HIGH: general (ansible-passwords)
══════════════════════════════════════════════════════════════════════════════════════════
Passwords in ansible host/group vars
──────────────────────────────────────────────────────────────────────────────────────────
 my.example.org/my.example.org.yml:4
──────────────────────────────────────────────────────────────────────────────────────────
   2   my_app2_********************
   3   my_app00_password: pa!vaultssword # false negative, wrong allow-rule regex
   4 [ my_app3_********************
   5   my_app4_password: <P4/55W0R<D # false negative, incomplete rule regex
──────────────────────────────────────────────────────────────────────────────────────────

# note: no false positive on msmtp_password
```

It would be nice if this could be refined and integrated into trivy. Thanks

### Target

Filesystem

### Scanner

Secret
