### DISCUSSION TITLE
Custom secrets not detected in repo

### DISCUSSION THREAD

**Discussion by ethoms-usgs** [aquasecurity/trivy#6454] [Q&A] [answered]
### Question

Started with Gitleaks and was able to get it to detect some fake secrets in a repository containing only two files, `fake_secrets.txt` and `requirements.txt`, using a custom configuration file. After migrating the rules over to YAML for Trivy, nothing is detected.

I run `trivy repo "path/to/repo' -c "path/to/trivy-secret.yaml` and get

```
2024-04-03T14:01:02.991-0800    INFO    Loaded path/to/repo
2024-04-03T14:01:02.997-0800    INFO    Vulnerability scanning is enabled
2024-04-03T14:01:02.997-0800    INFO    Secret scanning is enabled
2024-04-03T14:01:03.000-0800    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-04-03T14:01:03.000-0800    INFO    Please see also https://aquasecurity.github.io/trivy/v0.50/docs/scanner/secret/#recommendation for faster secret detection
2024-04-03T14:01:03.001-0800    INFO    Loading trivy-secret.yaml for secret scanning...
2024-04-03T14:01:03.011-0800    INFO    Number of language-specific files: 1
2024-04-03T14:01:03.011-0800    INFO    Detecting pip vulnerabilities...
```
and then no reports of secrets.

It took a bit of fiddling with a YAML linter to get the regexes properly formatted, but they differ from what was working with Gitleaks by only some escape characters and only three of the seven rules needed editing anyway.

I have tried disabling the examples allow-rule and scanning the repo as a file system.

### Target

Git Repository

### Scanner

Secret

### Output Format

Table

### Mode

Standalone

### Operating System

Windows 10

### Version

```bash
Version: 0.50.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-04-03 18:12:10.546555408 +0000 UTC
  NextUpdate: 2024-04-04 00:12:10.546554706 +0000 UTC
  DownloadedAt: 2024-04-03 21:45:48.6022329 +0000 UTC
Policy Bundle:
  Digest: sha256:cdff1bc8c97e4f5cd04782b057c00f5ea8cd81147a506ac4be76bef13710f2d3
  DownloadedAt: 2024-03-05 21:48:23.0160194 +0000 UTC
```

**Comment by AnaisUrlichs** [comment]
Hi there, what content is in the file? e.g. trivy-secret.yaml? Trivy will look for particular keywords/patterns that suggest there is a secret in the file, it does not understand the naming of the files itself 

Here is the entire docs on secret scanning https://aquasecurity.github.io/trivy/v0.50/docs/scanner/secret/

**Reply by ethoms-usgs** [reply]
Thank you. Well, the file is based on the examples at that link. It's entirely possible I simply don't know how to format good YAML, but the file passes the linter, and the report says it's getting loaded (I got a few errors about compiling until I fixed some regexes but trivy seems content now). I re-named the file so as to not possibly conflict with the `trivy-secret` expected in the current directory, but same report. I get a couple software vulnerabilities, but no secrets are detected. 

```
rules:
  - id: paths
    category: security_review
    title: find absolute windows paths
    severity: low
    regex: '''"?[a-zA-Z]:[^/]\\?\\?(?:[^\\/:*?"<>|\r\n]+?\\?\\)*[^\\/:*?"<>|\r\n]*"?'''
  - id: ip address
    category: security_review
    title: find numerical ip addresses
    severity: low
    regex: '''\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'''
  - id: email warning
    category: security_review
    title: find email addresses
    severity: low
    regex: '''[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$'''
  - id: AGOL warning
    category: security_review
    title: AGOL login warning
    severity: low
    regex: '''GIS\((.*?)\)'''
    keywords:
      - url
      - username
      - password
      - key_file
      - cert_file
      - verify_cert
  - id: Internal USGS server name
    description: Find internal USGS server name
    category: security_review
    regex: '''[A-Za-z0-9]+\.[A-Za-z0-9]+\.[A-Za-z0-9]+\.[A-Za-z0-9]+'''
    severity: low
  - id: ScienceBase login warning
    description: ScienceBase login warning
    category: security_review
    regex: (import sciencebasepy|sciencebasepy.SbSession\(\)|\.login\((.*?)\))
    keywords:
      - username
      - password
    severity: low
```

fake secrets file:
```C:\fake\path\to\folder with spaces
C:\ArcGIS\Pro
C:\ArcGIS\Desktop
user@company.xyz
user@agency.gov
from arcgis.gis import GIS
GIS(username="myfakeusername", password="myfakepassword")
255.255.255.255
FAKESERVER12.at.bureau.agency
import sciencebasepy
sciencebasepy.SbSession()
sb.login(user)
```
