### DISCUSSION TITLE
GitHub Dependency Graph fails with `invalid package url: in manifest "gobinary" decoding "": scheme is missing`

### DISCUSSION THREAD

**Discussion by MPV** [aquasecurity/trivy#6495] [Bugs]
### Description

`"message": "invalid package url: in manifest \"gobinary\" decoding \"\": scheme is missing",`

…when trying to do this (on an image):
- https://github.com/aquasecurity/trivy-action#using-trivy-to-generate-sbom

---

This is a follow-up issue on the now-closed:
- https://github.com/aquasecurity/trivy/discussions/5474

Specifically, there were some ideas by @DmitriyLewen over in:
- https://github.com/aquasecurity/trivy/issues/5449#issuecomment-1800969796
	> Looks like this is GitHub bug.
	> 
	> But It is strange. We don't fill purl field for local Go dependencies:
	> 
	> ```json
	>     {
	>       "name": "./api",
	>       "SPDXID": "SPDXRef-Package-cab1689fa6aee0c7",
	>       "versionInfo": "(devel)",
	>       "supplier": "NOASSERTION",
	>       "downloadLocation": "NONE",
	>       "licenseConcluded": "NONE",
	>       "licenseDeclared": "NONE",
	>       "copyrightText": "",
	>       "primaryPackagePurpose": "LIBRARY"
	>     },
	> ```
	> 
	> GitHub docs say that file must follow SPDX format - [docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exporting-a-software-bill-of-materials-for-your-repository](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exporting-a-software-bill-of-materials-for-your-repository) But `externalRefs` (field with purl) is not required field - [spdx.github.io/spdx-spec/v2.3/package-information/#721-external-reference-field](https://spdx.github.io/spdx-spec/v2.3/package-information/#721-external-reference-field).

### Desired Behavior

Dependency Graph uploaded, containing dependencies from the image. 

### Actual Behavior

```
[…]
Running trivy with options: trivy image  --format github --vuln-type  os,library --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --output  dependency-results.sbom.json  my-image:bf749f578bf01266a531bea9116ca69791d84aaf
[…]
2024-04-15T09:48:23.137Z	INFO	Detected OS: ubuntu
2024-04-15T09:48:23.137Z	INFO	Detecting Ubuntu vulnerabilities...
2024-04-15T09:48:23.144Z	INFO	Number of language-specific files: 2
2024-04-15T09:48:23.144Z	INFO	Detecting gobinary vulnerabilities...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

 Uploading GitHub Dependency Snapshot{
  "message": "invalid package url: in manifest \"gobinary\" decoding \"\": scheme is missing",
  "documentation_url": "https://docs.github.com/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository"
}
```

### Reproduction Steps

Using GitHub Actions:

```yaml
      - name: Scan image with Trivy, submit results to GitHub Dependency Graph
        uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # 0.19.0
        with:
          scan-type: 'image'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: "${{ env.IMAGE }}:${{ github.sha }}"
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: cat dependency-results.sbom.json
        run: |
          cat "dependency-results.sbom.json"
```

…on an image based on `ibm-semeru-runtimes:open-11-jdk-focal@sha256:735b94b802d2d9b13f9a8991e02f21b0f4810796e833fcd8a8726887c0216678` but added some more files, most interesting probably `vault` (being a Golang binary). 🤷‍♂️

Here's one of the two examples I see in my SBOM that matches `gobinary`:

```json
[...]
    "usr/local/bin/vault": {
      "name": "gobinary",
      "file": {
        "source_location": "usr/local/bin/vault"
      },
      "resolved": {
        "./api": {
          "relationship": "direct",
          "scope": "runtime"
        },
        "./api/auth/kubernetes": {
          "relationship": "direct",
          "scope": "runtime"
        },
        "./sdk": {
          "relationship": "direct",
          "scope": "runtime"
        },
        "cloud.google.com/go": {
          "package_url": "pkg:golang/cloud.google.com/go@v0.110.4",
          "relationship": "direct",
          "scope": "runtime"
        },
[...]
```

### Target

Container Image

### Scanner

None

### Output Format

None

### Mode

None

### Debug Output

```bash
N/A
```

### Operating System

Ubuntu-latest in GHA

### Version

```bash
aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # 0.19.0
```

### Checklist

- [ ] Run `trivy image --reset`
- [ ] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)
