### DISCUSSION TITLE
How to write custom checks for Terraform?

### DISCUSSION THREAD

**Discussion by mdirkse** [aquasecurity/trivy#7087] [Q&A]
### Question

I'm struggling to convert a custom check that we use in TFSec to Trivy.

The TFSec custom check ensures that the `default_tags` for the AWS provider in Terraform includes an `Application` tag:
```yaml
---
checks:
  - code: CUS001
    description: Check if the AWS provider has the default "Application" tag set for all supported resources.
    requiredTypes:
      - provider
    requiredLabels:
      - aws
    severity: ERROR
    matchSpec:
      name: default_tags
      action: isPresent
      subMatch:
        name: tags
        action: contains
        value: Application
    errorMessage: The Application tag in the "default_tags" configuration of the AWS provider was missing.
    relatedLinks:
      - https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags
```
I've been trying to convert this to Rego but the entire development experience so far has been pretty frustrating:

- Even in debug mode Trivy gives no indication that it has loaded my check.
- I know it is loading the check because when I intentionally break the syntax Trivy complains. But there is no indication of the check being applied to my files.
- The directory that I'm running Trivy against contains 4 `.tf` files, but for some completely inscrutable reason Trivy only appears to be checking 2 of them.
- The [docs](https://aquasecurity.github.io/trivy/v0.33/docs/misconfiguration/custom/debug/) say "_Only failed policies show traces. If you want to debug a passed policy, you need to make it fail on purpose._" I've tried myriad ways to make the check fail, but (apart form a stack overflow error) I haven't managed to do so. I don't even know if the check is being applied.
- The [docs](https://aquasecurity.github.io/trivy/v0.53/docs/scanner/misconfiguration/custom/debug/) also say "_Have a look at the [built-in checks](https://github.com/aquasecurity/trivy-checks/tree/main/checks) for Trivy for inspiration on how to write custom checks._" But all of the AWS checks in that directory seem to be implemented in Go, not in Rego.

It would be really helpful to have some actual examples of Rego checks for Terraform so I can see how they're supposed to be implemented (and applied). And it would be really helpful if Trivy was a bit more verbose about what checks it's loading, which ones it's applying, why it's ignoring certain Terraform files etc.

Currently my check is as follows:
```rego
# METADATA
# title: Enforce "Application" tag
# description: Check if the AWS provider has the default "Application" tag set for all supported resources.
# scope: package
# schemas:
#   - input: schema["cloud"]
# custom:
#   id: JMB-CUS-001
#   severity: CRITICAL
#   short_code: no-application-tag
#   recommended_action: "Add the 'Application' tag in the 'default_tags' configuration of the AWS provider."
#   input:
#     selector:
#     - type: cloud

package test.terraform.CUS001

default allow = false

deny[res] {
  default_tags := input.aws.meta.tfproviders[_].defaulttags
  default_tags.tags.value["Application"] != "bla"
  res := "The 'Application' tag is missing in the 'default_tags' configuration of the AWS provider."
}
```

And I (try to) invoke it using the following command:
```bash
trivy config --debug --trace \
    . \
    --exit-code 1 \
    --misconfig-scanners terraform,terraformplan-json,terraformplan-snapshot \
    --tf-exclude-downloaded-modules \
    --tf-vars dev.tfvars \
    --config-check ~/custom_checks \
    --check-namespaces test \
    --ignorefile ~/ignore-dir/trivy-ignore.yaml \
    --file-patterns "cloud:\.tf$"
```

### Target

AWS

### Scanner

Misconfiguration

### Output Format

Table

### Mode

Standalone

### Operating System

Linux

### Version

```bash
Version: 0.53.0
Check Bundle:
  Digest: sha256:ef2d9ad4fce0f933b20a662004d7e55bf200987c180e7f2cd531af631f408bb3
  DownloadedAt: 2024-07-02 09:48:31.364978325 +0000 UTC
```
