### DISCUSSION TITLE
Default config file doesn't contain `kubernetes` options

### DISCUSSION THREAD

**Discussion by afdesk** [aquasecurity/trivy#7258] [Bugs]
### Description

There are no `kubernetes` options in Trivy default config file now.

@chen-keinan could you confirm that config files work correctly for k8s scans? thanks!

### Desired Behavior

`trivy-default.yaml` contains next section:

```yaml
kubernetes:
  # Same as '--context'
  # Default is empty
  context:

  # Same as '--namespace'
  # Default is empty
  namespace:

  # Same as '--kubeconfig'
  # Default is empty
  kubeconfig: ~/.kube/config2

  # Same as '--components'
  # Default is 'workload,infra'
  components: 
    - workload
    - infra
```

### Actual Behavior

there is no `kubernetes` section

### Reproduction Steps

1.Generate default trivy config:
```sh
$ trivy image --generate-default-config
```
2. Look for `kubernetes` options
```sh
$ cat trivy-default.yaml | grep kubernetes
```
the output contains only `- kubernetes` for `scanners` block

### Debug Output
```sh
$ trivy image -d --generate-default-config
2024-07-30T12:03:43+06:00	DEBUG	Cache dir	dir="/home/user/.cache/trivy"
2024-07-30T12:03:43+06:00	DEBUG	Parsed severities	severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
2024-07-30T12:03:43+06:00	DEBUG	Ignore statuses	statuses=[]
2024-07-30T12:03:43+06:00	INFO	Writing the default config to trivy-default.yaml...
```

### Operating System

Ubuntu 22.04.4 LTS

### Version

```bash
$ trivy --version
Version: 0.53.0
```

### Checklist

- [X] Run `trivy clean --all`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)
