### DISCUSSION TITLE
Add the ability to pass start/end line values as configuration options in Misconfiguration ignorefile config

### DISCUSSION THREAD

**Discussion by michael-a-shelton** [aquasecurity/trivy#7325] [Ideas]
### Description

The proposal is to add the ability to define the start/end lines as optional config fields in the ignore file.
Currently:
```yaml
  - id: KSV048
    paths:
      - templates/test-template.yaml
```

Proposed:
```yaml
  - id: KSV048
    startLine: 9
    endLine: 11
    paths:
      - templates/test-template.yaml
```

This is a relatively non-invasive small change, adding two fields to the IgnoreFinding struct, passing the values from the calling functions into the `Match` method, where a conditional then does the line comparsions. The value add here is to allow more granular control over the explicit rules being ignored, instead of ignoring the rule across the entire rendered output, but over specific lines in the output.

I've made the change in a private fork and have it working and would like to propose pushing the change upstream.

### Target

None

### Scanner

Misconfiguration
