### DISCUSSION TITLE
Helm templates with implicit fields causes always OutOfSync in ArgoCD deployment

### DISCUSSION THREAD

**Discussion by LucasVanHaaren** [aquasecurity/trivy#7361] [Bugs]
### Description

Hello,
I tried to deploy trivy as a server for Client-Server mode via ArgoCD via the helm chart.
I face the issue that my app is always out of sync as the trivy StatefulSet dosent define the VolumeClaimTemplates's kind and apiVersion :

![image](https://github.com/user-attachments/assets/a7fb6b84-2c89-40e3-85a1-c6dd34df8d46)

PS: Git blaming show that it was always like this since the creation of the helm chart.

### Desired Behavior

The template should define `kind` and `apiVersion` in `volumeClaimTemplates` like this :

```yaml
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1	
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
```

### Actual Behavior

The kind and apiVersion are implicit so the templated manifests are different than the actual Kubernetes resources, which cause to be always OutOfSync in gitops-pull tools like argoCD.

### Reproduction Steps

1. Create kube manifests from helm chart
```bash
helm template trivy aquasecurity/trivy --namespace trivy-repro --set persistence.enabled=true | tee trivy-templates.yml
```

2. Check the manifest:
```bash
grep 'volumeClaimTemplates' trivy-templates.yml -b5
2877-  replicas: 1
2891-  selector:
2903-    matchLabels:
2920-      app.kubernetes.io/name: trivy
2956-      app.kubernetes.io/instance: trivy
2996:  volumeClaimTemplates:
3020-    - metadata:
3036-        name: data
3055-      spec:
3067-        resources:
3086-          requests:
```

3. Deploy manifests to a cluster:
```bash
kubectl create -f trivy-templates.yml
```

4. Check the kube resource:
```bash
k get sts trivy -o yaml | grep 'volumeClaimTemplates' -b5
2722-        name: tmp-data
2745-  updateStrategy:
2763-    rollingUpdate:
2782-      partition: 0
2801-    type: RollingUpdate
2825:  volumeClaimTemplates:
2849-  - apiVersion: v1
2868-    kind: PersistentVolumeClaim
2900-    metadata:
2914-      creationTimestamp: null
2944-      name: data
```

### Mode

Client/Server

### Operating System

Kubernetes

### Version

- trivy `0.37.2`
- Chart `0.7.0`

### Checklist

- [ ] Run `trivy clean --all`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)
