### DISCUSSION TITLE
Trivy update fails

### DISCUSSION THREAD

**Discussion by gwitsch** [aquasecurity/trivy#7538] [Q&A] [answered]
### Question

Hello,

recently trivy is having issues updating the database before scanning container images.

To isolate the problem, I have introduced a separate update task which runs the update-only commands.
The problem only occurs at our nightly build pipeline run betwenn 8pm - 11pm.

Here is the update commands output:

> 21:00:20  Trivy: updating vulnerability DB ...
[Pipeline] sh
21:00:21  + trivy image --debug --download-db-only --cache-dir /home/jenkins/trivy_cache --timeout 15m --no-progress
21:00:21  2024-09-16T19:00:21Z	DEBUG	Cache dir	dir="/home/jenkins/trivy_cache"
21:00:21  2024-09-16T19:00:21Z	DEBUG	Parsed severities	severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
21:00:21  2024-09-16T19:00:21Z	DEBUG	Ignore statuses	statuses=[]
21:00:21  2024-09-16T19:00:21Z	INFO	[db] Need to update DB
21:00:21  2024-09-16T19:00:21Z	INFO	[db] Downloading DB...	repository="ghcr.io/aquasecurity/trivy-db:2"
21:00:22  2024-09-16T19:00:22Z	FATAL	Fatal error
21:00:22    - init error:
21:00:22      github.com/aquasecurity/trivy/pkg/commands/artifact.Run
21:00:22          /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:358
21:00:22    - DB error:
21:00:22      github.com/aquasecurity/trivy/pkg/commands/artifact.NewRunner
21:00:22          /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:119
21:00:22    - failed to download vulnerability DB:
21:00:22      github.com/aquasecurity/trivy/pkg/commands/operation.DownloadDB
21:00:22          /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:41
21:00:22    - database download error:
21:00:22      github.com/aquasecurity/trivy/pkg/db.(*Client).Download
21:00:22          /home/runner/work/trivy/trivy/pkg/db/db.go:162
21:00:22    - oci download error:
21:00:22      github.com/aquasecurity/trivy/pkg/oci.(*Artifact).Download
21:00:22          /home/runner/work/trivy/trivy/pkg/oci/artifact.go:144
21:00:22    - failed to fetch the layer:
21:00:22      github.com/aquasecurity/trivy/pkg/oci.(*Artifact).download
21:00:22          /home/runner/work/trivy/trivy/pkg/oci/artifact.go:158
21:00:22    - GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:15a6fd375dca7d4d11fde458d5ba5f3fa60832e93da70143ad9e9e188d8d8c07: TOOMANYREQUESTS: retry-after: 576.466µs, allowed: 44000/minute

From my point of view, it looks like it's a problem related to the Github container registry. I guess there is some kind of DDoS protection in place.

Has anyone already faced the same issue? Or already found a solution?

Best regards,
Gotthard

### Target

Container Image

### Scanner

None

### Output Format

None

### Mode

Standalone

### Operating System

Ubuntu

### Version

```bash
0.54.1
```

**Comment by nikpivkin** [comment]
Hi @gwitsch !

We have encountered the same thing at CI and are still looking into the problem.

**Reply by synack-security** [reply]
I have seen this as well

**Comment by simar7** [comment]
Please see https://aquasecurity.github.io/trivy/v0.55/docs/references/troubleshooting/#github-rate-limiting

**Reply by synack-security** [reply]
That is a different error than what we are seeing.  Also, why all of the sudden would all these different deployments of Trivy just start failing on this at the same time?

**Reply by simar7** [reply]
Right but does the problem go away if you use a GH Token as described above? Just trying to debug the root cause.

**Reply by gwitsch** [reply]
I can give it a try for debugging.

But it also appears to be strange to stop working just over night. It's reasonable that there are more users now, but i think that should not be a problem for GHCR. At least any DDoS protection or rate limiting process should not be triggered. As the the log message in GitHub Rate limiting documentation states, there should ba an output containing the requestor's IP.

I'll setup a Github token and clear the caches. Next nightly builds might show, if the problem still occurs.

**Reply by knqyf263** [reply]
I've opened a ticket.
https://github.com/orgs/community/discussions/139074

**Reply by acastong** [reply]
For those that my have a on site registry that can act as a cache for remote content, the following environment variables can prevent the problem by making Trivy pull from the cache on not hit the ghcr pull limit:

```
TRIVY_DB_REPOSITORY=${registryCacheHost}/${ghcr-cache-path}/aquasecurity/trivy-db \
TRIVY_JAVA_DB_REPOSITORY=${registryCacheHost}/${ghcr-cache-path}/aquasecurity/trivy-java-db
```

where `registryCacheHost` is you caching registry fqdn and `ghcr-cache-path` is the project/repo in your registry that is configured to cache ghcr.io

**Reply by gwitsch** [reply]
Adding a Github token seems to be working. At least the last couple of days, the update process worked as expected.

**Reply by synack-security** [reply]
I added a token and 1 out of 2 scans still failed.  Haven’t seen any failures since Thursday though without using token.

**Reply by gwitsch** [reply]
Sadly, Github tokens don't fix the issue.
Our nightly builds failed with the same exception:
``` 
23:01:35    - 1 error occurred:
23:01:35  	* GET https://ghcr.io/v2/aquasecurity/trivy-java-db/manifests/1: TOOMANYREQUESTS: retry-after: 140.905µs, allowed: 44000/minute
```

**Reply by knqyf263** [reply]
Same here.
https://github.com/aquasecurity/trivy/pull/7580#issuecomment-2370624673

**Comment by knqyf263** [comment]
We published trivy-db in [Amazon ECR Public Gallery](https://gallery.ecr.aws/aquasecurity/trivy-db) as well as GHCR.
https://github.com/aquasecurity/trivy-db/pull/440

The following should work now. We'll update the documentation tomorrow.

```
trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 YOUR_IMAGE
```

**Reply by knqyf263** [reply]
EDITED: We hope to do the same for trivy-java-db.

**Reply by synack-security** [reply]
You need to do “trivy-db” instead of “trivy-db:2” for the image as trivy adds the version when it runs.

**Reply by synack-security** [reply]
@knqyf263 when is the javadb in ECR going to get rolled out?

**Reply by knqyf263** [reply]
>You need to do “trivy-db” instead of “trivy-db:2” for the image as trivy adds the version when it runs.

No, it's not true. `trivy-db:2` is legitimate. `trivy-db` works just for backward compatibility.
https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/flag/db_flags.go#L156-L161

**Reply by knqyf263** [reply]
>@knqyf263 when is the javadb in ECR going to get rolled out?

No ETA. We're asking our internal team.

**Reply by knqyf263** [reply]
Published
https://github.com/aquasecurity/trivy-java-db/pull/37

Note that ECR Public also has quotas. We'll document it.

**Reply by prezha** [reply]
we occasionally hit the `TOOMANYREQUESTS` as well, so i worked on a pr that would add retry with exponential backoff to db download on this specific error - if maintainers would like to review the pr, i'm happy to create it
the [pr](https://github.com/aquasecurity/trivy/compare/main...prezha:trivy:retry-db-download) is ready, with unit and integration tests passing locally

**Reply by dannystaple** [reply]
Is there a way to use that ECR public image with the trivy github action? (at least until that new release is made available)?

**Reply by knqyf263** [reply]
You can use [trivy.yaml](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#trivy-config-file).
https://aquasecurity.github.io/trivy/v0.55/docs/references/configuration/config-file/#db-options

```
db:
  repository: "public.ecr.aws/aquasecurity/trivy-db:2"
```

@simar7 Please correct me if I'm wrong.

**Reply by carek88** [reply]
Just in case someone struggles with the config file in case of github action - I find it easier to do it by settting an env variable:
```
env:
  TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
```

**Reply by Debabrata47** [reply]
I have also added the public ecr but still got rate limit issue,sometimes it works sometimes it not:
trivy image --timeout=10m -d --db-repository public.ecr.aws/aquasecurity/trivy-db:2 -f json -o result.json --severity CRITICAL $IMAGE
2024-10-07T08:43:51Z	DEBUG	Parsed severities	severities=[CRITICAL]
2024-10-07T08:43:51Z	DEBUG	Ignore statuses	statuses=[]
2024-10-07T08:43:51Z	DEBUG	Cache dir	dir="/root/.cache/trivy"
2024-10-07T08:43:51Z	DEBUG	There is no valid metadata file	err="unable to open a file: open /root/.cache/trivy/db/metadata.json: no such file or directory"
2024-10-07T08:43:51Z	INFO	Need to update DB
2024-10-07T08:43:51Z	INFO	Downloading DB...	repository="public.ecr.aws/aquasecurity/trivy-db:2"
2024-10-07T08:43:51Z	DEBUG	No metadata file
26.36 MiB / 54.04 MiB [----------------------------->_______________________________] 48.78% ? p/s ?54.04 MiB / 54.04 MiB [----------------------------------------------------------->] 100.00% ? p/s ?54.04 MiB / 54.04 MiB 	DEBUG	Updating database metadata...
2024-10-07T08:43:56Z	DEBUG	DB info	schema=2 updated_at=2024-10-07T06:17:04.462736974Z next_update=2024-10-08T06:17:04.462736814Z downloaded_at=2024-10-07T08:43:56.427506289Z
2024-10-07T08:43:56Z	INFO	Vulnerability scanning is enabled
2024-10-07T08:43:56Z	DEBUG	Vulnerability type	type=[os library]
2024-10-07T08:43:56Z	INFO	Secret scanning is enabled
2024-10-07T08:43:56Z	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-10-07T08:43:56Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.51/docs/scanner/secret/#recommendation for faster secret detection
2024-10-07T08:43:56Z	DEBUG	Enabling misconfiguration scanners	scanners=[azure-arm cloudformation dockerfile helm kubernetes terraform terraformplan-json terraformplan-snapshot]
2024-10-07T08:43:56Z	DEBUG	[secret] No secret config detected	config_path="trivy-secret.yaml"

2024-10-07T08:45:42Z	FATAL	Fatal error
  - image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:422
  - OCI repository error:
    github.com/aquasecurity/trivy/pkg/oci.(*Artifact).populate
        /home/runner/work/trivy/trivy/pkg/oci/artifact.go:93
  - 1 error occurred:
	* GET https://ghcr.io/v2/aquasecurity/trivy-java-db/manifests/1: TOOMANYREQUESTS: retry-after: 854.879µs, allowed: 44000/minute

**Reply by FirelightFlagboy** [reply]
Hi @Debabrata47,

Your command fail because it try to download the java vuln db from `ghcr.io`.
You need to add `--java-repository public.ecr.aws/aquasecurity/trivy-java-db`

> Not sure about the URL

**Reply by Debabrata47** [reply]
alright gotcha!

But is there any solution like to eliminate the need to download DB from aquasecurity because even if we use public ecr pretty sure it might be having rate limit as well.

How about download the DB and storing it in S3 and fetching it and if this correct way how will the Tricy command change??

**Reply by ryan-cpi** [reply]
Is there a way Trivy by default could use ECR rather than GitHub if it returns ratelimit errors? So having a list of databases to call in order 1, Github 2. ECR 3. Private S3

**Reply by thomascaillier** [reply]
@ryan-cpi `--db-repository` and `--java-db-repository` now accept a list (see https://github.com/aquasecurity/trivy/commit/3562529ddfb26d301311ed450c192e17011353df)

**Reply by thomascaillier** [reply]
@knqyf263 is it planned to set these new repositories as default ones ? (in addition of the GHCR one, or not)

**Reply by knqyf263** [reply]
We're careful about that.
https://github.com/aquasecurity/trivy/pull/7679#issuecomment-2404376752

**Reply by Connor-Wood** [reply]
@thomascaillier 

We tried the list: `trivy image --db-repository ghcr.io/aquasecurity/trivy-db:2 public.ecr.aws/aquasecurity/trivy-db:2`
and are seeing an error on only the first one. In what cases are the following repos tried?

2024-10-14T14:45:11Z	INFO	[db] Need to update DB
2024-10-14T14:45:11Z	INFO	[db] Downloading DB...	repository="ghcr.io/aquasecurity/trivy-db:2"
2024-10-14T14:45:11Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: database download error: oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:8dcb18f131bc5d8d17159f7682ebd49b2ea9c784edbb03aa87fe92927ff1d851: TOOMANYREQUESTS: retry-after: 36.478µs, allowed: 44000/minute

**Reply by thomascaillier** [reply]
@Connor-Wood  i'm sorry i don't know, i just saw it in the docs

**Reply by fxnn** [reply]
@Connor-Wood

I would guess that you used a slightly wrong command line syntax. Not sure how `trivy` will parse it, but probably it should be either of these:

```
trivy image --db-repository ghcr.io/aquasecurity/trivy-db:2 --db-repository public.ecr.aws/aquasecurity/trivy-db:2
trivy image --db-repository ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
```

Because the way you did it, trivy won't understand that the second repo's URI belongs to the `--db-repository` flag.

**Reply by ktzsolt** [reply]
@knqyf263 Could you please populate the trivy-chekcs repo too on ecr? https://gallery.ecr.aws/aquasecurity/trivy-checks

**Reply by knqyf263** [reply]
@ktzsolt I'm not an owner of that. It's being discussed here. https://github.com/aquasecurity/trivy-checks/pull/262

**Reply by zwdnet** [reply]
it works for me. Thanks!

**Comment by ryan-cpi** [comment]
I've not been able to get a successful Trivy run in GitLab for the last few hours due to this issue. We've seen it on and off in the past but all of our installs fail 100% now. This is causing our pipelines to fail so we can no longer merge code.
```
2024-10-01T12:18:51Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
	* GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 545.68µs, allowed: 44000/minute
Python Version 3.12.6 (main, Sep 12 2024, 21:15:48) [GCC 13.2.1 20240309]
```

**Reply by knqyf263** [reply]
For the short term, try https://github.com/aquasecurity/trivy/discussions/7538#discussioncomment-10741936. For the long term, please consider storing the database in the cache.

**Reply by prezha** [reply]
@knqyf263 do you think it would make sense to implement the [retry](https://github.com/aquasecurity/trivy/discussions/7538#discussioncomment-10802516) in case of the TOOMANYREQUESTS db download error?

**Reply by ryan-cpi** [reply]
This has been happening for a few hours and none of the manual retrys seem to help. For the long term fix of using a cache is there any recommended way that's documented for doing this with GitLab runners?
We already use `--cache-dir .trivycache/ `but that will only be shared between jobs in a pipeline.
```
Trivy_SCA:
  cache:
    paths:
      - .trivycache/

```

**Reply by knqyf263** [reply]
@prezha As @ryan-cpi pointed out, the situation may not improve within a few hours. We're very careful about retrying because retrying may increase the number of requests and make the situation worse. We'll probably introduce retry in the future, but we want to add more mitigations first.

**Reply by knqyf263** [reply]
>This has been happening for a few hours and none of the manual retrys seem to help. For the long term fix of using a cache is there any recommended way that's documented for doing this with GitLab runners?

I'm not familiar with GitLab, so we need help from someone who knows it well. However, according to the document, the cache seems to be shared between pipelines. Am I missing something?

>Subsequent pipelines can use the cache.

https://docs.gitlab.com/ee/ci/caching/#cache

**Reply by prezha** [reply]
> @prezha As @ryan-cpi pointed out, the situation may not improve within a few hours. We're very careful about retrying because retrying may increase the number of requests and make the situation worse. We'll probably introduce retry in the future, but we want to add more mitigations first.

that makes sense, thank you for providing the context

**Reply by ryan-cpi** [reply]
> For the short term, try https://github.com/aquasecurity/trivy/discussions/7538#discussioncomment-10741936. For the long term, please consider storing the database in the cache.

The long term solution doesn't seem to be working for us as we had this in place long before these issues have been popping up. For the short term solution being using ECR how frequently is this image updated as I don't want to be pointing to an image that will only be updated short term? 

Is there a long-term solution we can use or are we good to permanently use the ECR image from now on?

**Reply by bartvollebregt** [reply]
> I'm not familiar with GitLab, so we need help from someone who knows it well. However, according to the document, the cache seems to be shared between pipelines. Am I missing something?
> 

@knqyf263 If you need any help with Gitlab configuration, let me know.

This is what our Gitlab job looks like:

```
container_scanning:
  stage: verify
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/aquasec/trivy:latest
    entrypoint: [""]
  only:
    - schedules
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db:2
    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  before_script:
    - apk --no-cache add curl
  script:
    - trivy --version
    - time trivy clean --scan-cache
    - time trivy image --download-db-only
    - trivy image --scanners vuln --vuln-type os --exit-code=1 --severity='HIGH,CRITICAL' -q "$FULL_IMAGE_NAME"
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
```

We're still facing issues with the TOOMANYREQUESTS error though. 

As you can see we're using a cache:key: value here. This defines when the cache is re-used in another job. In this case I'm using a hardcoded string value, so each pipeline job **in the same repository** will use the same cache. However, we have a lot of different projects and repository and it's not possible to share cache across repositories in Gitlab (due to security reasons and cache poisoning).

**Reply by fxnn** [reply]
> TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db:2

Does this work for you? Because (on GitHub Actions btw) with

```
env:
    TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
```

I'm getting

```
2024-10-23T20:20:22Z	FATAL	Fatal error	flag error: db flag error: invalid db repository: could not parse reference: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
```

**Reply by bartvollebregt** [reply]
> > TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db:2
> 
> Does this work for you? Because (on GitHub Actions btw) with
> 
> ```
> env:
>     TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
> ```
> 
> I'm getting
> 
> ```
> 2024-10-23T20:20:22Z	FATAL	Fatal error	flag error: db flag error: invalid db repository: could not parse reference: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
> ```
It works fine for me on all of our Gitlab projects.
I tested it locally as well and seems to work fine:
```
$ export TRIVY_DB_REPOSITORY=ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db:2
$ trivy image --scanners vuln --vuln-type os "postgres:16"
2024-11-14T16:24:02+01:00       WARN    '--vuln-type' is deprecated. Use '--pkg-types' instead.
2024-11-14T16:24:02+01:00       INFO    Adding schema version to the DB repository for backward compatibility   repository="ghcr.io/aquasecurity/trivy-db:2"
2024-11-14T16:24:02+01:00       INFO    Adding schema version to the DB repository for backward compatibility   repository="public.ecr.aws/aquasecurity/trivy-db:2"
2024-11-14T16:24:02+01:00       INFO    [vulndb] Need to update DB
2024-11-14T16:24:02+01:00       INFO    [vulndb] Downloading vulnerability DB...
2024-11-14T16:24:02+01:00       INFO    [vulndb] Downloading artifact...        repo="ghcr.io/aquasecurity/trivy-db:2"
55.50 MiB / 55.50 MiB [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 20.98 MiB p/s 2.8s
2024-11-14T16:24:05+01:00       INFO    [vulndb] Artifact successfully downloaded       repo="ghcr.io/aquasecurity/trivy-db:2"
2024-11-14T16:24:05+01:00       INFO    [vuln] Vulnerability scanning is enabled
....
```

**Comment by bryanhermass** [comment]
I found an option to create a local cache by setting the environment variable TRIVY_CACHE_DIR=<path> and using the command trivy --download-db-only. It downloads the database to the specified path, and when scanning images, it won't connect to https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2.

I think this could solve the issue.

Doc : https://aquasecurity.github.io/trivy/v0.56/docs/advanced/air-gap/#populating-the-trivy-cache

**Reply by kapi-caz** [reply]
Thank you, @bryanhermass,
This works for us as well. In case anyone is using Azure DevOps, use the [cache task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines) and use `/home/vsts/.cache/trivy` as path.

**Reply by karl18** [reply]
@kapi-caz I'm using AZ DevOps, but only specifying cache folder is not a solution, didn't try to add '--download-db-only' but here is the question, why I need this flag, and what will it affect if I'm using like this in the future ?

**Reply by karl18** [reply]
It’s not working with me on Az DevOps even when specifying both flags  TRIVY_CACHE_DIR= + --download-db-only.

**Reply by karl18** [reply]
@bryanhermass  @kapi-caz  does anyone bypassed the error on az devops ? how ? I tried as mentioned adding two flags but still see the errors

**Reply by rofehaim** [reply]
@karl18 yes, I managed to use cache in azure devops pipelines and it solves the issue (at least in the meantime).
since I'm running the trivy via docker image I had to specify a cache folder inside the container, and I saw that trivy map /tmp as volume so I used '--cache-dir /tmp/trivy-cache' and it worked.
this is the full yaml task:

> task: trivy@1
> displayName: Vulnerabilities scan
> inputs:
>   version: 'latest'
>   debug: true
>   image: '${{ parameters.registry}}/${{ parameters.imageName }}:$(Build.BuildNumber)'
>   severities: 'CRITICAL,HIGH'
>   ignoreUnfixed: true
>   options: '--timeout 15m0s --cache-dir /tmp/trivy-cache'

**Comment by lucaovieira** [comment]
But when you need to update your database the issue keep happen. I use github actions here and the solution that I had to use was cache for the db and config file changing the repository to new one that they sent here and the issues is happens much less now.

**Comment by QuinnBast** [comment]
I tried all of the suggestions above. Running on Gitlab, enabled artifacts for the `.trivycache` with key names, I set `TRIVY_DB_REPOSITORY` and `TRIVY_CACHE_DIR` but my trivy commands are still failing (they appear to be making calls to download the latest databases even though I have a cache...

```
$ time trivy image --download-db-only
2024-10-31T15:38:20Z	INFO	[vulndb] Need to update DB
2024-10-31T15:38:20Z	INFO	[vulndb] Downloading vulnerability DB...
2024-10-31T15:38:20Z	INFO	[vulndb] Downloading artifact...	repo="ghcr.io/aquasecurity/trivy-db:2"
2024-10-31T15:38:21Z	ERROR	[vulndb] Failed to download artifact	repo="ghcr.io/aquasecurity/trivy-db:2" err="oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:b4b4f730819548e788f047001aaea24b40a5227db588422482d3086d2937a552: TOOMANYREQUESTS: retry-after: 890.582µs, allowed: 44000/minute"
2024-10-31T15:38:21Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source
```

I am scanning ~6-7 images in seperate pipelines so it makes sense that I am hitting some rate-limit, but I cannot figure out how I am supposed to be configuring this cache to work properly... 

I think the *real* issue is that `trivy image --download-db-only` is not skipping the database download even if a cache already exists. I figured having a cache, the cache would tell it "hey, I just updated 2 minutes ago, don't look to pull database vulnerabilities for another 7 days", for example. But this does not appear to be happening.

Am I missing a CLI flag or something?

**Reply by QuinnBast** [reply]
Update: I ended up cloning the docker images to a local docker registry and using that in my CI/CD pipelines and I was able to resolve the issue. The problem is the cloning of the `ghcr.io` docker images gets rate-limited.

To solve it I used [skopeo](https://github.com/containers/skopeo) to copy the image (since it is OCI docker cannot copy it) into our artifactory instance, and then pointed my pipeline to my company's artifactory instance.

```
skopeo copy --format=oci docker://ghcr.io/aquasecurity/trivy-java-db:1 docker://artifactory.mydomain.com/docker-mirror/aquasecurity/trivy-java-db:1
skopeo copy --format=oci docker://ghcr.io/aquasecurity/trivy-db:2 docker://artifactory.mydomain.com/docker-mirror/aquasecurity/trivy-db:2
```

This is my pipeline:

```yaml
container_scan:
  stage: containerize
  # https://aquasecurity.github.io/trivy/v0.18.3/usage/image/
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [ "" ]
  variables:
    # No need to clone the repo
    GIT_STRATEGY: none

    # Variables to authenticate to our private registry
    TRIVY_USERNAME: "$JFROG_CI_USER"
    TRIVY_PASSWORD: "$JFROG_CI_PASSWORD"
    TRIVY_AUTH_URL: "$ARTIFACTORY_REGISTRY"

    # Misc.
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"

    # Configure Trivy to pull the database images from our local private images instead of ghcr.io
    TRIVY_DB_REPOSITORY: artifactory.mydomain.com/docker-mirror/aquasecurity/trivy-db:2
    TRIVY_JAVA_DB_REPOSITORY: artifactory.mydomain.com/docker-mirror/aquasecurity/trivy-java-db:1

    # The image I want scanned
    FULL_IMAGE_NAME: ${ARTIFACTORY_REGISTRY}/${CONTAINER_NAME}:${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
  script:
    # Dump version.
    - trivy --version

    # Clear out the previous scan history from the cache
    - time trivy clean --scan-cache

    # update databases
    - time trivy image --download-db-only
    - time trivy image --download-java-db-only

    # Builds report and puts it in the default workdir $CI_PROJECT_DIR, so `artifacts:` can take it from there
    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"

    # Prints full report to the console
    - time trivy image --exit-code 0 "$FULL_IMAGE_NAME"

    # Fail on critical vulnerabilities
    - time trivy image --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json
```

Hopefully this helps some future souls. Though it's a bit rough for people who don't have any way to mirror docker images to some local cache/registry...

> I think the *real* issue is that `trivy image --download-db-only` is not skipping the database download even if a cache already exists.

Turns out this was happening because I have 10 CI/CD runners and the trivy cache only gets placed onto individual runners. So the trivy cache was runner dependent, and getting a different CI/CD runner would caus the image to get pulled again. Something to keep in mind if you are using multiple runners...

**Comment by LukaK** [comment]
Anyone trying to run it locally as part of pre-commit checks when pushing the code upstream?
Sometimes it passes, sometimes I have to run it 3-4 times to download changes and finish the scan.

```yaml
default_stages:
  - pre-commit

repos:
  - repo: local
    hooks:

      - id: trivy-fs
        stages:
          - pre-push
        name: trivy-fs
        language: docker_image
        entry: -v /tmp:/.cache aquasec/trivy:latest fs -c .config/trivy.yaml .
        pass_filenames: false
```
