### DISCUSSION TITLE
TOOMANYREQUESTS errors when downloading java-db from ghcr.io

### DISCUSSION THREAD

**Discussion by sakky016** [aquasecurity/trivy#7591] [Q&A] [answered]
### Question

**Issue in java-db download**
This is in follow-up to discussion this thread - https://github.com/orgs/community/discussions/139074#discussioncomment-10739491.

Shouldn't trivy check some sort of release-info/metadata before trying to download java-db? This release-info could indicate that a new java-db is available, perhaps by using content-hash of the available java-db). If new java-db is not available or has failed (just like this issue-https://github.com/aquasecurity/trivy-java-db/actions), then trivy should not attempt to download the artifact at all.

The current logic is dependent on the publishing process of java-db and the schedule of download is governed by NextUpdate field of metadata.json. With this approach trivy always attempts to download java-db (even if the one that is available is older or has failed). This logic does not consider that future publishing of java-db could fail.

### Target

Container Image

### Scanner

Vulnerability

### Output Format

JSON

### Mode

Standalone

### Operating System

LInux

**Comment by knqyf263** [comment]
Yes, your suggestion makes sense. We already compare the content hash for misconfiguration checks to prevent the bundle from being downloaded unnecessarily. We can do the same for trivy-java-db as well.
https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/policy/policy.go#L172-L175

On the other hand, we have `DownloadedAt` to mitigate this kind of problem. For example, trivy-db checks `DownloadedAt` and will not download the database too frequently.
https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/db/db.go#L142-L145

I didn't find the same logic in trivy-java-db. Did we forgot to add it or am I missing something? @DmitriyLewen 
https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/javadb/client.go#L56

**Reply by DmitriyLewen** [reply]
@knqyf263 we have been implementing `trivy-java-db` at an accelerated pace  (because maven servers work unstable) - so it looks like we really forgot to take this into account (although we are updating this field):
https://github.com/aquasecurity/trivy/blob/8d0ae1f5de72d92a043dcd6b7c164d30e51b6047/pkg/javadb/client.go#L77

**Reply by knqyf263** [reply]
OK. Can we quickly implement it?

**Reply by DmitriyLewen** [reply]
I think so. We just need to add another `if` for `DownloadedAt`.
I will try to do that today.

But I think 1 hour (as for `trivy-db`) is too small.
What if we use 1 day?

**Reply by DmitriyLewen** [reply, marked as answer]
@knqyf263 https://github.com/aquasecurity/trivy/pull/7592

**Comment by durcon** [comment]
BTW: What is the reason to load `trivy-db` every 6 hours?

```
2024-09-30T12:14:02Z	DEBUG	DB update was skipped because the local DB is the latest
2024-09-30T12:14:02Z	DEBUG	DB info	schema=2 updated_at=2024-09-30T06:14:28.338986152Z next_update=2024-09-30T12:14:28.338985871Z downloaded_at=2024-09-30T12:06:18.039677019Z
```

For Trivy 17.x I could read in the docs that it is downloaded every 12 hours. In the docs for Trivy 55 I don't find anything about it.

**Reply by DmitriyLewen** [reply]
Due to the current situation, perhaps we should think about reducing the update frequency of trivy-db
@knqyf263

**Reply by knqyf263** [reply]
@durcon It's written here.
https://aquasecurity.github.io/trivy/v0.55/docs/scanner/vulnerability/#vulnerability-database

@DmitriyLewen Users can specify `--skip-db-update` if they want to skip updates. They can create a cron workflow to pull the database and store it in the cache every 6 hours, 12 hours or 24 housrs, for example, and create another workflow to scan for vulnerabilities with `--skip-db-update`, like we did for test images.

**Reply by knqyf263** [reply]
You can use the cache. We plan to document it better.

**Reply by Ksoftcode** [reply]
I had the offline cache and CRON update every 12 hours implemented using Azure File Share and Jenkins for updates and CRON job. However, a new experience is that Trivy Java DB pulls from the docker hub every runtime instead of being cached like Trivy DB. Is there a reason why Trivy Java DB is treated differently?

**Comment by gnomefin** [comment]
For those who are still facing issues, according to maintainer's suggestion, this below snippet highlights the example quick fix code that I created:

- Using oras to fetch/pull the offline db
- store airgapped (offline DB) to cache 
- caching condition
- The execution is always using `--skip-db-update`

(this is for trivy-db, if you are using java version, you can adjust it accordingly)
```
name: Trivy Scan
description: "This action is intended to run Trivy in an air-gapped environment."
inputs:
  trivy-image-ref:
    description: "Trivy image reference based on repository and tags"
    required: true
  trivy-gcp-artifact-registry:
    description: "Artifact registry in GCP"
    required: true
    default: me-central2-docker.pkg.dev

runs:
  using: composite
  steps:
    - name: GCloud Auth WIP Dev
      id: gcloud-auth
      uses: <org>/actions-workflows/actions/modules/workload-identity-provider/generic@main

    # Install Oras CLI to pull Trivy DB v2
    - name: Install Oras CLI
      shell: bash
      run: |
        curl -sSL https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz | tar -xz -C /usr/local/bin oras

    # Install Trivy
    - name: Install Trivy
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.55.2

    # Set up cache for Trivy database, include version in the cache key
    - name: Set Up Trivy Cache
      id: trivy-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy/db
        key: ${{ runner.os }}-trivy-db-cache

    # Only download the Trivy offline database if cache miss
    - name: Download Trivy Offline Database
      if: steps.trivy-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        oras pull ghcr.io/aquasecurity/trivy-db:2
        ls -lah

    # Only extract the database if cache miss
    - name: Set Up Trivy Database in Cache
      if: steps.trivy-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.cache/trivy/db
        tar -xvf db.tar.gz -C ~/.cache/trivy/db

    # Run Trivy using the offline database
    - name: Run Trivy Vulnerability Scanner
      shell: bash
      run: |
        trivy --cache-dir ~/.cache/trivy image --exit-code 0 --format table --ignore-unfixed --severity CRITICAL,HIGH --skip-db-update ${{ inputs.trivy-image-ref }}
```

Still failed to fetch? You can wait until the rate limit period is over or we can use AWS ECR mirror to trigger fetch, then as soon as it is available to fetch, run it and store to cache.
