### DISCUSSION TITLE
feat(helm): Add annotations to service

### DISCUSSION THREAD

**Discussion by lchastel** [aquasecurity/trivy#7929] [Ideas]
### Description

I need to add annotation to the service, but the field is not available in the template helm/trivy/templates/service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "trivy.fullname" .) }}
  labels:
    {{ include "trivy.labels" . | indent 4 }}
```

**begin of modification**
```yaml
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```
**end of modification**

```yaml
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "trivy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: trivy-http
      protocol: TCP
      port: {{ .Values.service.port | default 4954 }}
      targetPort: {{ .Values.service.port | default 4954 }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "ClientIP" }}
```

### Target

None

### Scanner

None
