### DISCUSSION TITLE
How to fix cross-spawn (package.json) vulnerability

### DISCUSSION THREAD

**Discussion by nikunjworld** [aquasecurity/trivy#8071] [Q&A]
### Question

We have travy enabled on node js project, it is reporting cross-spawn  CVE-2024-21538 from version: 7.0.3. Since it is not directly used in package.json however it is indirectly reported from Jest lib which has dependency on execa, so reported vulnerability is from execa lib. So I wanted to know how can I fix it as it is an indirect dependency. Although I added overrides section in package.json as advised from online. But travy is still reporting it, please let me know how to fix it.

`"overrides": {
    "execa":"7.0.0"
  },`

### Target

Git Repository

### Scanner

Vulnerability

### Output Format

None

### Mode

None

### Operating System

family="alpine" version="3.20.3"

### Version

```bash
aquasec/trivy:latest
```

**Comment by DmitriyLewen** [comment]
Hello @nikunjworld 
Thanks for your interest to Trivy!

Did you run `npm update` to update `package-lock.json` file?

**Reply by nikunjworld** [reply]
Hi Dmitry,

Thanks for your response, trivy reported the error after pushing my changes to the gitlab pipeline. So do you mean to add the `npm update` command in the gitlab deployment step?

**Reply by DmitriyLewen** [reply]
Can you send more information about using Trivy and your repository?

Trivy scans `package-lock.json` files in `repo` mode.
If you use `overrides` - you need to update `package-lock.json` file after updating `package.json` file.

If your `package-lock.json` file already contains the correct version - please send me that file (or another test file with this error) for investigation.

**Reply by nikunjworld** [reply]
Following is the screenshot of package-lock.json file with "overrides": {
    "execa":"6.0.0"
  }
![image](https://github.com/user-attachments/assets/d834637e-29c6-424f-a7f7-83d89bba3fd6)
In above screenshot you notice that cross-spawn version is 7.0.3 which is not changing even if I override execa with latest version and trivy is reporting this 7.0.3 from cross-spawn with vulnerability.

Another fact is I installed trivy extension locally on vs code, when I ran trivy scan locally it is not reporting this vulnerability.

Below is my gitlab pipeline step to execute trivy. Which might help. Also note that I am not using execa or cross-spawn directly but since I am using jest lib it is reporting from that lib, jest version : "jest": "29.7.0"

```
trivy_scan_qa:
  stage: trivy_scan_qa
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  # needs: 
  #   - sonar_analysis
  script:
    # - export IMAGE_TAG_QA="scan-$CI_COMMIT_SHORT_SHA" 
    - IMAGE_TAG_QA="qa-$CI_COMMIT_SHORT_SHA"
    - sudo docker build -t $IMAGE_TAG_QA -f dockerfiles/qa/Dockerfile .
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:latest image --severity CRITICAL,HIGH --exit-code 1 --scanners vuln $IMAGE_TAG_QA:latest
#    - trivy image --severity CRITICAL,HIGH --exit-code 1 --scanners vuln $IMAGE_TAG_QA:latest
  only:
    - /^(qa)+-?.*$/  
  except:
    - branches
  allow_failure: true
```

gitlab pipeline screenshot:

![image](https://github.com/user-attachments/assets/3eb173e4-bc0f-4281-a93d-d9c766f6c6d1)
