### DISCUSSION TITLE
bug(misconf): unquoted merge key is not processed in YAML config files

### DISCUSSION THREAD

**Discussion by nikpivkin** [aquasecurity/trivy#8263] [Bugs]
### Description

Trivy uses `gopkg.in/yaml.v3` to decode YAML that [does not support](https://github.com/go-yaml/yaml/issues/245) << ([merge](https://yaml.org/type/merge.html)) unquoted keys.

[Example configuration](https://github.com/GoogleCloudPlatform/click-to-deploy/blob/6439d579a4840951036be987ae2863344fb5682c/k8s/knative/chart/knative/templates/knative/eventing/mtping.yaml#L26-L40):

```yaml
...
spec:
  # when set to 0 (and only 0) will be set to 1 when the first PingSource is created.
  replicas: {{ .Values.knative.eventing.mtping.replicas }}
  selector:
    matchLabels: &labels
      eventing.knative.dev/source: ping-source-controller
      sources.knative.dev/role: adapter
  template:
    metadata:
      labels:
        !!merge <<: *labels
        eventing.knative.dev/release: "v1.9.0"
        app.kubernetes.io/component: pingsource-mt-adapter
        app.kubernetes.io/version: "1.9.0"
        app.kubernetes.io/name: knative-eventing
...
```

Perhaps we could use the [goccy/go-yaml](https://github.com/goccy/go-yaml) package, which is actively maintained and passes all the test cases from the YAML Test Suite, but I haven't looked to see if the package has the ability to get the YAML node position.

### Desired Behavior

The merge key will be processed

### Actual Behavior

The merge key is considered just a map key

### Reproduction Steps

```bash
...
```

### Target

None

### Scanner

None

### Output Format

None

### Mode

None

### Debug Output

```bash
...
```

### Operating System

m1

### Version

```bash
0.58.0
```

### Checklist

- [X] Run `trivy clean --all`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)
