### DISCUSSION TITLE
Degrade performance of the k8s cluster scanning in v0.59

### DISCUSSION THREAD

**Discussion by unmade** [aquasecurity/trivy#8373] [Bugs]
### Description

I noticed a significant difference in performance for k8s cluster scanning between `v0.58` and `v0.59`. The `v0.59` takes approx. 10x more time to complete.

Here is the command I'm running:
```bash
trivy \
  --report all \
  --format json \
  --scanners vuln \
  k8s \
  "$SCAN_CONTEXT" \
  --include-namespaces "$SCAN_NAMESPACES" \
  --exclude-kinds replicationcontrollers,daemonsets,cronjobs,jobs,services,configmaps,roles,rolebindings,networkpolicies,ingresses,resourcequotas,limitranges,clusterroles,clusterrolebindings \
  --disable-node-collector \
  --debug
```

Trivy is granted the following role:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-trivy-scanner
rules:
- apiGroups:
    - ""
    - "apps"
  resources:
    - deployments
    - namespaces
    - nodes
    - pods
    - replicasets
    - secrets
    - serviceaccounts
    - statefulsets
  verbs:
    - get
    - list
    - watch
```

I tried local runs as well as runs from within k8s cluster.

I don't get much information from the output other than on v0.59 the waiting time is significantly more than for v0.58. Any help into how to debug/profile where the bottleneck would be appreciated!

### Desired Behavior

Performance remains the same for k8s cluster scanning in version 0.59

### Actual Behavior

Performance degraded the same for k8s cluster scanning in version 0.59

### Reproduction Steps

```bash
Have a k8s cluster with few deployments, replicasets, statefulsets. Grant Trivy Role as in the example above. 

1. Run the scan with Trivy v0.58.3
2. Run the scan with Trivy v0.59.1
```

### Target

Kubernetes

### Scanner

Vulnerability

### Output Format

JSON

### Mode

Standalone

### Debug Output

```bash
There is no much difference in the output between 0.58 and 0.59, other that 0.59 takes much longer to complete.
```

### Operating System

macOS / Docker container deployed to k8s

### Version

```bash
$ trivy --version
Version: 0.58.3

$ trivy --version
Version: 0.59.1
```

### Checklist

- [X] Run `trivy clean --all`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)
