### DISCUSSION TITLE
Unknown blobs during scanning

### DISCUSSION THREAD

**Discussion by landbaychrisburrell** [aquasecurity/trivy#8745] [Q&A]
### Question

Hi

I've installed trivy operator on my EKS cluster using the helm chart. No special values, beyond the security context. For some containers, i get results, but for my java containers I don't - and instead I get this error:

``` {"level":"info","ts":"2025-04-16T15:09:39Z","logger":"KubeAPIWarningLogger","msg":"unknown field \"report.vulnerabilities[57].packagePURL\""}                                                                {"level":"error","ts":"2025-04-16T15:10:06Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy/scan-vulnerabilityreport-5d557cb64b","container":"document-generation-service","status.reason":"Error","status.message":"2025-04-16T15:10:03Z\tFATAL\tFatal error\timage scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:f0e9078fd509b2493bcef1215b4de825d53f118ef0648b850edec03dc6e3cfd4): post analysis error: post analysis error: Unable to initialize the Java DB: Java DB update failed: OCI artifact error: failed to download Java DB: failed to download artifact from any source: 1 error occurred:
\t* oci download error: failed to fetch the layer: GET https://mirror.gcr.io/v2/aquasec/trivy-java-db/blobs/sha256:2cb3c31c934a568169c2b41542b31b7c90b6db310f58c85d45dce94e3ed6bb92: BLOB_UNKNOWN: Unknown blob: sha256:2cb3c31c934a568169c2b41542b31b7c90b6db310f58c85d45dce94e3ed6bb92","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).completedContainers
\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:355
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1
\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:82
sigs.k8s.io/controller-runtime/pkg/reconcile.TypedFunc[...].Reconcile
\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/reconcile/reconcile.go:124
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249"}                     
```

I also get a warning saying 
`{"level":"info","ts":"2025-04-16T15:10:31Z","logger":"KubeAPIWarningLogger","msg":"unknown field \"report.vulnerabilities[37].packagePURL\""}    `

When running the kubectl get commands, i get results (presumably for those that haven't failed). 
` kubectl get vulnerabilityreports --all-namespaces -o wide`

Have I done something wrong?

My values.yaml looks somewhat like this:
```
  values:
    trivyOperator:
      scanJobPodTemplateContainerSecurityContext:
        seccompProfile:
          type: "RuntimeDefault"
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      scanJobPodTemplatePodSecurityContext:
        seccompProfile:
          type: "RuntimeDefault"
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    podSecurityContext:
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    securityContext:
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
```

Other containers that download DBs seem to operate OK:
```
Downloading artifact...    repo="mirror.gcr.io/aquasec/trivy-db:2" 
```

Any pointers on where to look next?

### Target

Container Image

### Scanner

Vulnerability

### Output Format

None

### Mode

None

### Operating System

EKS/Bottlerocket

### Version

```bash
Trivy operator: 0.25.0
```
