### DISCUSSION TITLE
Misconfiguration reports about ConfigMap with secrets, when in reality it's a UNIX variable

### DISCUSSION THREAD

**Discussion by AsiaWinner** [aquasecurity/trivy#8865] [False Detection]
### IDs

AVD-KSV-0109

### Description

We have config that looks like this:

```
kubectl describe configmap x-configuration --namespace x-namespace

Data
====
application.yaml:
----
___company_name___:
  gigahub:
    cucumber:
      environment: dev
      summary: "_____"
      tags: "_____"
      features-folder: "_____"

      monitor:
        - "_____"
      jira:
        url: "_____"
        access-token: ${SOME_ACCESS_TOKEN}
        private-key: ${SOME_PRIVATE_KEY}
        consumer-key: ${SOME_CONSUMER_KEY}
        read-timeout: 60000
        export-results:
          enabled: false
        import-features:
          enabled: true
          tql: "_____"
      integrations:
```

Then I run trivy scan that includes this config:
```
trivy k8s --report summary --severity HIGH,CRITICAL --timeout 1h -d --skip-images --format json --disable-node-collector --scanners misconfig,secret -o trivy_scan.json
```

In the end, trivy reports on the "ConfigMap with secrets" misconfig for the key "access-token":

```
          "Misconfigurations": [
            {
              "Type": "Kubernetes Security Check",
              "ID": "AVD-KSV-0109",
              "AVDID": "AVD-KSV-0109",
              "Title": "ConfigMap with secrets",
              "Description": "Storing secrets in configMaps is unsafe",
              "Message": "ConfigMap 'x-configuration' in 'x' namespace stores secrets in key(s) or value(s) '{\"        access-token\"}'",
              "Namespace": "builtin.kubernetes.KSV0109",
              "Query": "data.builtin.kubernetes.KSV0109.deny",
              "Resolution": "Remove password/secret from configMap data value",
              "Severity": "HIGH",
              "PrimaryURL": "https://avd.aquasec.com/misconfig/avd-ksv-0109",
              "References": [
                "https://avd.aquasec.com/misconfig/avd-ksv-0109"
              ],
              "Status": "FAIL",
              "Layer": {},
              "CauseMetadata": {
                "Provider": "Kubernetes",
                "Service": "general",
                "Code": {
                  "Lines": null
                },
                "RenderedCause": {}
              }
            }
          ]
```

This probably should not be reported as a misconfiguration, since there is no ACTUAL secret stored, only a UNIX variable that is safe to reference.

If this is how it's intended to work, then how could I filter out this misconfiguration on my side? I've tried the "--ignore-policy" flag with the .rego file, but I don't think there is a way to get the value of the "access-token" field inside of it:

"Failed" example:

```
package trivy

default ignore = false

ignore {
  input.ID == "AVD-KSV-0109"
  input.Type == "Kubernetes Security Check"

  # how to get value of the "access-token" field here???
  value := input.something

  # check if the field's value is a unix variable of format ${SECRET_TOKEN}
  re_match("^.*\\$\\{.*$", value)
}
```

### Reproduction Steps

```bash
Please write to me if you need the reproduction steps, because it would take me some time to write the step-by-step instruction.
```

### Target

Kubernetes

### Scanner

Misconfiguration

### Target OS

Ubuntu 22

### Debug Output

```bash
Please comment if you need the debug output here.
```

### Version

```bash
0.62
```

### Checklist

- [X] Read [the documentation regarding wrong detection](https://trivy.dev/dev/community/contribute/discussion/#false-detection)
- [X] Ran Trivy with `-f json` that shows data sources and confirmed that the security advisory in data sources was correct
