### DISCUSSION TITLE
Trivy Filesystem Scan fails running on Docker Container on MacOS

### DISCUSSION THREAD

**Discussion by alohasick** [aquasecurity/trivy#8975] [Bugs]
### Description

I'm not able to run Secret scan on a MacOS laptop using Trivy Docker Container. It works fine using the same configuration when using the executable installed using Homebrew. It also works fine on Ubuntu with both executable and Docker image.

It seems to always get stuck on scanning a file. I tried skipping the file but all it was get stuck on the next one.

The directory being mounted into the container volume is located inside the `/users` space so the container user should have the right permissions.

This is the content of my `trivy_config.yaml`:
```yaml
exit-code: 1
format: table
quiet: true
timeout: 1m0s
offline: true
secret:
  config: /workdir/.husky/secret_detection_rules.yaml
scan:
  detection-priority: precise
  parallel: 5
  show-suppressed: false
  scanners:
    - secret
  skip-dirs:
    - ./**/.amplify/**/*
    - ./**/.next/**/*
    - ./mypy-cache/**/*
    - ./**/.nx/**/*
    - ./coverage/**/*
    - ./dist/**/*
    - ./instrumented/**/*
    - ./junit-reports/**/*
    - ./node-modules/**/*
    - ./test-data/**/*
    - ./tmp/**/*
  skip-files:
    - ./.env.local
```

### Desired Behavior

Should be able to run Trivy Secret Scan on MacOS using a Docker image

### Actual Behavior

Scan fails or times out.

### Reproduction Steps

```bash
1. Run Secret Scanning using Docker Container on a Mac
```

### Target

Filesystem

### Scanner

Secret

### Output Format

Table

### Mode

Standalone

### Debug Output

```bash
$ time docker run --rm -v "$(pwd):/workdir" -i --rm aquasec/trivy:latest fs /workdir --config="/workdir/.husky/trivy_config.yaml" -d
2025-06-03T13:31:53Z	FATAL	Fatal error
  - run error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:408
  - fs scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:446
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:285
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:675
  - failed analysis:
    github.com/aquasecurity/trivy/pkg/scan.Service.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scan/service.go:166
  - analyze with traversal:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.Inspect
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/local/fs.go:185
  - walk dir error:
    github.com/aquasecurity/trivy/pkg/fanal/walker.(*FS).Walk
        /home/runner/work/trivy/trivy/pkg/fanal/walker/fs.go:35
  - unknown error with /workdir/.eslintignore:
    github.com/aquasecurity/trivy/pkg/fanal/walker.(*FS).Walk.(*FS).onError.func2
        /home/runner/work/trivy/trivy/pkg/fanal/walker/fs.go:92
  - failed to analyze file:
    github.com/aquasecurity/trivy/pkg/fanal/walker.(*FS).Walk.(*FS).WalkDirFunc.func1
        /home/runner/work/trivy/trivy/pkg/fanal/walker/fs.go:73
  - analyze file (.eslintignore):
    github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.analyzeWithTraversal.func1
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/local/fs.go:278
  - semaphore acquire:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.AnalyzeFile
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:443
  - context deadline exceeded
docker run --rm -v "$(pwd):/workdir" -i --rm aquasec/trivy:latest fs /workdir  0.01s user 0.02s system 0% cpu 1:53.14 total
```

### Operating System

15.3.2 (24D81)

### Version

```bash
0.63.0
```

### Checklist

- [ ] Run `trivy clean --all`
- [X] Read [the troubleshooting](https://trivy.dev/latest/docs/references/troubleshooting/)
