### ISSUE TITLE
GitHub Action - analysis fails after sarif upload

### ISSUE THREAD

**Issue by mgmgwi** [aquasecurity/trivy#1038]
## Description

I'm scanning a docker image and want to upload the result via the `github/codeql-action/upload-sarif@v1` action.

```
name: Trivy Analysis

on:
  push:

jobs:
  trivy_analysis:
    name: Trivy Analysis
    runs-on: "ubuntu-18.04"
    steps:
      - name: Run Trivy on python:3.6-slim-buster
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.6-slim-buster'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-slim-buster.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload works fine, but analysis fails
      - name: Upload Trivy slim-buster scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-slim-buster.sarif'
```

## What did you expect to happen?

sarif file gets analyzed correctly.

## What happened instead?

The error 'Analysis failed for trivy-workflow' is shown on the Code scanning alerts tab.

![Trivy Analysis Fails](https://user-images.githubusercontent.com/43027257/120437617-94866d00-c380-11eb-8cb4-cf0ebb05b044.png)

## Output of run with `-debug`:

```
not available
```

## Output of `trivy -v`:

```
Run aquasecurity/trivy-action@master
  with:
    image-ref: python:3.6-slim-buster
    format: template
    template: @/contrib/sarif.tpl
    output: trivy-slim-buster.sarif
    severity: CRITICAL,HIGH
    scan-type: image
    scan-ref: .
    exit-code: 0
    ignore-unfixed: false
    vuln-type: os,library
/usr/bin/docker run --name a33c1b243f0bb5ad54f939442448bb6a70f7e_e14d32 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_IMAGE-REF -e INPUT_FORMAT -e INPUT_TEMPLATE -e INPUT_OUTPUT -e INPUT_SEVERITY -e INPUT_SCAN-TYPE -e INPUT_INPUT -e INPUT_SCAN-REF -e INPUT_EXIT-CODE -e INPUT_IGNORE-UNFIXED -e INPUT_VULN-TYPE -e INPUT_SKIP-DIRS -e INPUT_CACHE-DIR -e INPUT_TIMEOUT -e INPUT_IGNORE-POLICY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/indy-node-container/indy-node-container":"/github/workspace" 8a33c1:b243f0bb5ad54f939442448bb6a70f7e  "-a image" "-b template" "-c @/contrib/sarif.tpl" "-d 0" "-e false" "-f os,library" "-g CRITICAL,HIGH" "-h trivy-slim-buster.sarif" "-i python:3.6-slim-buster" "-j ." "-k " "-l " "-m " "-n " "-o "
Running trivy with options:  --no-progress  --format  template --template  @/contrib/sarif.tpl --exit-code  0 --vuln-type  os,library --severity  CRITICAL,HIGH --output  trivy-slim-buster.sarif  python:3.6-slim-buster
Global options:  
2021-06-02T06:51:17.428Z	INFO	Need to update DB
2021-06-02T06:51:17.429Z	INFO	Downloading DB...
2021-06-02T06:51:20.595Z	INFO	Detecting Debian vulnerabilities...
2021-06-02T06:51:20.605Z	INFO	Trivy skips scanning programming language libraries because no supported file was detected
```

## Additional details (base image name, container registry info...):

Uploading the result file to the [Microsoft SARIF validator](https://sarifweb.azurewebsites.net/) shows these problems:

- GH1003: runs[0].results[0].locations[0].physicalLocation: The 'region' property is absent. GitHub Advanced Security code scanning can display the correct location only for results that provide a 'region' object with line and optional column information. At minimum, 'region.startLine' is required. 'region' can also provide 'startColumn', 'endLine', and 'endColumn', although all of those have reasonable defaults.
- GH1005: runs[0].results[0].locations[0].physicalLocation.artifactLocation.uri: 'python:3.6-slim-buster' is not a file path. GitHub Advanced Security code scanning only displays results whose locations are specified by file paths, either as relative URIs or as absolute URIs that use the 'file' scheme.
- SARIF1004: runs[0].results[0].locations[0].physicalLocation.artifactLocation: This 'artifactLocation' object has a 'uriBaseId' property 'ROOTPATH', but its 'uri' property 'python:3.6-slim-buster' is an absolute URI. Since the purpose of 'uriBaseId' is to resolve a relative reference to an absolute URI, it is not allowed when the 'uri' property is already an absolute URI.
- SARIF2012: runs[0].tool.driver.rules[0].name: 'OS Package Vulnerability (Debian)' is not a Pascal-case identifier. For uniformity of experience across all tools that produce SARIF, the friendly name should be a single Pascal-case identifier, for example, 'ProvideRuleFriendlyName'.

I don't know whether these problems are the cause of the error, but maybe they can be fixed by adjusting this block 

https://github.com/aquasecurity/trivy/blob/fb19abd09acc39c06a132fab8d0b9181f1556dcb/contrib/sarif.tpl#L76-L80

if a Docker image is scanned.
