### ISSUE TITLE
Trivy Plugin Install Missing Some files

### ISSUE THREAD

**Issue by shpml** [aquasecurity/trivy#1084]
I'm currently creating a plugin to export trivy results to csv format and upload to my cloud provider.

My plugin git repository contains the following files                                                                                                            
-  README.md
-  plugin.yaml
-  trivy_plugin.sh
-  trivy_full_csv.tpl
-  trivy_simple_csv.tpl

When I install the plugin with `trivy plugin install "git@bitbucket.org:my_org/trivy-plugin"` there are only two files downloaded to the plugin directory `.trivy/plugins/`. The `plugin.yaml` and `trivy_plugin.sh`, both template files are missing, along with the README but I don't need that. 

I've tried uninstalling the plugin and reinstalling and tried force installing a specific ref that I know contain those `.tpl` files but have had no luck.

Is there something I'm missing in order to get the `.tpl` files installed too? 

`plugin.yaml` contents are as follows if that has any bearing on the install.
```
name: "plugin"
repository: git@bitbucket.org:my_org/trivy-plugin
version: "0.0.2"
usage: Save as CSV
description: |-
  A Trivy plugin that saves as CSV.
  Usage: trivy plugin ....
platforms:
  - selector: # optional
      os: darwin
      arch: amd64
    uri: ./trivy_plugin.sh
    bin: ./trivy_plugin.sh
  - selector: # optional
      os: linux
      arch: amd64
    uri: ./trivy_plugin.sh
    bin: ./trivy_plugin.sh
```
