### ISSUE TITLE
Could not scan CloudFormation script using Trivy

### ISSUE THREAD

**Issue by Lingom-KSR** [aquasecurity/trivy#1507]
Hi,
I'm trying to use trivy for container images and IaC files. Able to scan the container images and the results are as mentioned in the [trivy](https://aquasecurity.github.io/trivy/v0.21.3/vulnerability/scanning/image/) doc.

For IaC scan, trivy is not scanning CloudFormation script. However, it's scanning other IaC scripts such as terraform, docker and kube; I'm able to see results for them.

The model of the cloudformation script is like the below one.

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: '.....'
Parameters:
  Ec2VolumeAutoEnableIO:
    Type: String
    Default: 'false'
    AllowedValues:
    - 'false'
    - 'true'
  Ec2VolumeTagKey:
    Type: String
    Default: CostCenter
Resources:
  Ec2Volume:
    Type: AWS::EC2::Volume
    Properties:
      AutoEnableIO:
        Ref: Ec2VolumeAutoEnableIO
      Size: '5'
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      Tags:
      - Key:
          Ref: Ec2VolumeTagKey
        Value: Ec2VolumeTagValue
```

Any help would be much appreciated.  Thanks!
