### ISSUE TITLE
Missing fingerprint option in codequality template

### ISSUE THREAD

**Issue by Jasstkn** [aquasecurity/trivy#1540]
## Description

Hi! I've been testing trivy with reporting feature for Gitlab Merge Requests reports. It seems that template is missing a required field (see https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool)

## What did you expect to happen?

I expect to see the generated report.

## What happened instead?

<img width="919" alt="Screenshot 2022-01-04 at 21 18 44" src="https://user-images.githubusercontent.com/20466436/148118688-c238d41f-ef85-4fca-969a-f946236c0a82.png">

No report has been shown

## Additional details (base image name, container registry info...):

Example of the `.gitlab-ci.yml`:
```
scan_image:
  stage: scan
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - docker
  needs:
    - dockerfile_lint
  variables:
    # Override the GIT_STRATEGY variable in your `.gitlab-ci.yml` file and set it to `fetch` if you want to provide a `clair-whitelist.yml`
    # file. See https://docs.gitlab.com/ee/user/application_security/container_scanning/index.html#overriding-the-container-scanning-template
    # for details
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    IMAGE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"
  allow_failure: true
  before_script:
    - apk add --no-cache curl jq
    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $TRIVY_VERSION
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
  script:
    - trivy image --clear-cache
    # update vulnerabilities db
    - trivy image --download-db-only --no-progress
    - trivy image --exit-code 0 --no-progress --format template --template "@contrib/gitlab-codequality.tpl" -o trivy-codeclimate.json $IMAGE
    - trivy image --exit-code 0 --no-progress "$IMAGE"

  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      codequality: trivy-codeclimate.json
  only:
    refs:
      - branches
```

The following object in the report has been generated:
```
  {
    "type": "issue",
    "check_name": "container_scanning",
    "categories": [
      "Security"
    ],
    "description": "CVE-2021-38561: ",
    "content": "",
    "severity": "info",
    "location": {
      "path": "golang.org/x/text-v0.3.2",
      "lines": {
        "begin": 1
      }
    }
  },
```

Working report from hadolint contains the fingerprint field:
```
  {
    "location": {
      "path": "Dockerfile",
      "lines": {
        "begin": 1,
        "end": 1
      }
    },
    "fingerprint": "66d91daf6d924e1cc1a74e6a4c52b916058d2661",
    "severity": "info",
    "check_name": "DL3049",
    "categories": [
      "Bug Risk"
    ],
    "type": "issue",
    "description": "Label `team` is missing."
  }
```
