### ISSUE TITLE
ServiceAccount annotations in helm chart are broken

### ISSUE THREAD

**Issue by dowlingw** [aquasecurity/trivy#1794]
## Description
The ServiceAccount annotations implemented for #1676 contains a bug that renders invalid YAML.

## What did you expect to happen?
Provide `trivy.serviceAccount.annotations` value and have valid YAML generated.

## What happened instead?
YAML generated with incorrect indentation level for `annotations` block on Trivy ServiceAccount resource:

```
# Source: redacted/charts/trivy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redacted-trivy
  labels:
    app.kubernetes.io/name: trivy
    helm.sh/chart: trivy-0.4.12
    app.kubernetes.io/instance: redacted
    app.kubernetes.io/version: "0.24.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::redacted:role/redcated
        eks.amazonaws.com/sts-regional-endpoints: true
```

## Additional details (base image name, container registry info...):
Tested using chart version `0.4.12`
