### ISSUE TITLE
Scan for image built in a previous stage of a TravisCI build looks instead in the docker registry

### ISSUE THREAD

**Issue by bogdanbarna** [aquasecurity/trivy#198]
**Description**

When running as part of a TravisCI build, scanning an image built a stage before fails returning the following error: `FATAL	error in image scan: failed to analyze image: failed to extract files: Get https://registry-1.docker.io/v2/ORG/APP/manifests/latest: http: non-successful response (status=401 body="{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"ORG/APP\",\"Action\":\"pull\"}]}]}\n")`.
On my local machine it works as expected.

**What did you expect to happen?**
Expected the scan to run for the local image built on a previous stage in the TravisCI build.
This is what I'm running for the trivy part:
```#!/usr/bin/env bash

set -v
set -e


# Exit if no $DOCKER_IMAGE_NAMESPACE variable is present
if [[ -z "$DOCKER_IMAGE_NAMESPACE" ]]; then
	exit 1
fi

export TRIVY_TIMEOUT_SEC=360s

# Use trivy binary if installed, else install it
if hash trivy 2>/dev/null; then
  TRIVY=trivy
else
  TRIVY_DIR="${HOME}/trivy"
  TRIVY="${TRIVY_DIR}/trivy"

  mkdir -p "${HOME}/trivy"
  VERSION=$(curl --silent https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r '.tag_name' | sed -E 's/[A-Za-z]+//')
  VERSION="0.1.6"
  TARBALL="trivy_${VERSION}_Linux-64bit.tar.gz"
  wget "https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/${TARBALL}"
  tar xzvf "${TARBALL}" -C "${TRIVY_DIR}"
  chmod 700 "${TRIVY}"
fi

$TRIVY --clear-cache --ignore-unfixed --exit-code 0 --severity HIGH --no-progress --auto-refresh "$DOCKER_IMAGE_NAMESPACE"
$TRIVY --clear-cache --ignore-unfixed --exit-code 1 --severity CRITICAL --no-progress --auto-refresh "$DOCKER_IMAGE_NAMESPACE"

exit 0
```

**What happened instead?**
The error message pasted above.

**Output of `trivy -v`:**

```
trivy version 0.1.6
```

**Additional details (base image name, container registry info...):**
The TravisCI build OS is set to Ubuntu Trusty and this is a snippet from .travis.yml for the build and scan stages:
```
    - stage: "Build"
      name: "Docker build"
      script:
        - docker --version && scripts/docker_build.sh
      env: DOCKER_BUILDKIT=1
    - stage: "Security scan"
      name: "Security scan"
      script:
        # Scan $DOCKER_IMAGE_NAMESPACE before pushing it to private registry
        - scripts/trivy_wrapper.sh
```
