### ISSUE TITLE
False positive avd-aws-0089 s3 bucket logging

### ISSUE THREAD

**Issue by isuftin** [aquasecurity/trivy#2157]
## Description

```
MEDIUM: Bucket does not have logging enabled
════════════════════════════════════════
Buckets should have logging enabled so that access can be audited.
See https://avd.aquasec.com/misconfig/avd-aws-0089
────────────────────────────────────────
 cloudformation.yml:5-19
────────────────────────────────────────
   5 ┌   MyS3Bucket:
   6 │     Type: AWS::S3::Bucket
   7 │     DeletionPolicy: Retain
   8 │     UpdateReplacePolicy: Retain
   9 │     Properties:
  10 │       BucketName: !Sub my-s3-bucket-${BucketSuffix}
  11 │       LoggingConfiguration:
  12 │         DestinationBucketName: !FindInMap [EnvironmentMapping, s3, logging]
  13 │         LogFilePrefix: !Sub s3-logs/AWSLogs/${AWS::AccountId}/my-s3-bucket-${BucketSuffix}
  14 │       AccessControl: Private
  15 │       PublicAccessBlockConfiguration:
  16 │         BlockPublicAcls: true
  17 │         BlockPublicPolicy: true
  18 │         IgnorePublicAcls: true
  19 └         RestrictPublicBuckets: true
```

Actual YML since the above is formatted poorly:

```yml
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub my-s3-bucket-${BucketSuffix}
      LoggingConfiguration:
        DestinationBucketName: !FindInMap [EnvironmentMapping, s3, logging]
        LogFilePrefix: !Sub s3-logs/AWSLogs/${AWS::AccountId}/my-s3-bucket-${BucketSuffix}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```
## What did you expect to happen?

No errors to come up when it comes to logging

## What happened instead?

Failed with avd-aws-0089

## Output of run with `-debug`:

```
trivy -debug config cloudformation/cloudformation.yml
2022-05-19T11:53:55.041-0500    DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-05-19T11:53:55.089-0500    DEBUG   cache dir:  /Users/isuftin/Library/Caches/trivy
2022-05-19T11:53:55.089-0500    DEBUG   Vulnerability type:  []
2022-05-19T11:53:55.280-0500    DEBUG   OS is not detected.
2022-05-19T11:53:55.280-0500    INFO    Detected config files: 1
2022-05-19T11:53:55.280-0500    DEBUG   Scanned config file: cloudformation.yml
2022-05-19T11:53:55.321-0500    DEBUG   Found an ignore file .trivyignore
2022-05-19T11:53:55.322-0500    DEBUG   These IDs will be ignored: ["AVD-AWS-0087" "AVD-AWS-0088" "AVD-AWS-0090" "AVD-AWS-0093" "AVD-AWS-0132"]

cloudformation.yml (cloudformation)

Tests: 5 (SUCCESSES: 4, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)

MEDIUM: Bucket does not have logging enabled
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Buckets should have logging enabled so that access can be audited.

See https://avd.aquasec.com/misconfig/avd-aws-0089
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 cloudformation.yml:5-19
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   5 ┌   MyS3Bucket:
   6 │     Type: AWS::S3::Bucket
   7 │     DeletionPolicy: Retain
   8 │     UpdateReplacePolicy: Retain
   9 │     Properties:
  10 │       BucketName: !Sub my-s3-bucket-${BucketSuffix}
  11 │       LoggingConfiguration:
  12 │         DestinationBucketName: !FindInMap [EnvironmentMapping, s3, logging]
  13 │         LogFilePrefix: !Sub s3-logs/AWSLogs/${AWS::AccountId}/my-s3-bucket-${BucketSuffix}
  14 │       AccessControl: Private
  15 │       PublicAccessBlockConfiguration:
  16 │         BlockPublicAcls: true
  17 │         BlockPublicPolicy: true
  18 │         IgnorePublicAcls: true
  19 └         RestrictPublicBuckets: true
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

## Output of `trivy -v`:

```
trivy -v
Version: 0.28.0
```
