### ISSUE TITLE
k8s: scan open secrets on resources

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy#2215]
Let's add support to open secrets on k8s resources (configmap, podsec, etc). Eg:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: default
data:
  AWS_ACCESS_KEY_ID: "XXX"
  AWS_SECRET_ACCESS_KEY: "XXX"
```
