### ISSUE TITLE
misconfig: kubernetes resource not indetified

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy#2284]
When passing cpu limits or requests with floating points, the file is not identified:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ubuntu:latest
        resources:
          limits:
            cpu: 0.5
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 80
```

But if we wrap the number in a string, it works:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ubuntu:latest
        resources:
          limits:
            cpu: "0.5"
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 80
```
