### ISSUE TITLE
Feature: add Github Action support

### ISSUE THREAD

**Issue by hazcod** [aquasecurity/trivy#233]
Github action workflows allow for a Docker image stored in a github repository to be scanned daily, on a pull request and a merge/push to a branch.
The results can then be reported in an issue ticket.

**Comment by hazcod** [comment]
Currently I am doing it with the following Github action, but since the database has a size of 1.7GB for alpine alone, it cannot be cached...

```
  dockerscan:
    name: docker security scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker build
      run: docker build . --file Dockerfile --tag image
    - name: cached scan db
      uses: actions/cache@preview
      with:
        path: vulndb/
        key: trivy-vulndb
    - name: run security scan
      env:
        DISTRO: alpine
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)/vulndb/":/root/.cache/ \
          aquasec/trivy --severity HIGH,CRITICAL,MEDIUM --no-progress --only-update $DISTRO --ignore-unfixed --exit-code 1 --cache-dir /root/.cache/ image
        docker run --rm -v "$(pwd)/vulndb/":/root/.cache/ alpine:latest chmod 777 -R /root/.cache/
```
