### ISSUE TITLE
custom-compliance reports

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy#2919]
when doing a misconfiguration scanning, trivy will evaluate all the possible checks and report the failed checks. this issue is about allowing the user to specify a subset of checks to be evaluated, essentially a custom report, that is more targeted at a specific use-case than the very general scanning experience that is today. 

### Motivation
1. we get asked to support compliance frameworks or security guidelines, which could be supported as a custom report.
1. as more checks are being added, the results become overwhelming. we are about to add checks from CloudSploit, which currently map to compliance frameworks but after migration will just get mixed up.
1. as more checks are being added, conflicting checks might exists (but in the context of a report/compliance framework checks are curated to be compatible)
1. can help organizing which checks to add, based on reports/frameworkds needed to be supported
1. users can create custom curated lists of checks

### History and prior work
In tfsec, checks are tagged to belong to different compliance frameworks. the `--framework` flag allows the user to filter checks based on tag. The common rules in defsec also supports this but Trivy today doesn't leverage this funtionality.

In [Starboard](https://github.com/aquasecurity/starboard), we added a [compliance mechanism](https://github.com/aquasecurity/starboard/pull/1004) that allows the user to specify a list of checks IDs, and it will be populated by the operator. This feature is [disabled in trivy-operator](https://github.com/aquasecurity/trivy-operator/issues/102) (starboard's successor)

### Design
likely something similar to Starboard's compliance, where a report is defined in YAML that selects a set of checks IDs (and some metadata about the report). We would have a list of reports built into Trivy, which the user can select from using a flag.
The user can also create a custom report in the same YAML format, and evaluate it.

**Comment by chen-keinan** [comment]
## Compliance Specification example :
```yaml
---
spec:
  name: nsa
  description: National Security Agency - Kubernetes Hardening Guidance
  version: "1.0"
  controls:
    - name: Non-root containers
      description: 'Check that container is not running as root'
      id: '1.0'
      mapping:
        scanner: config
        checks:
          - id: KSV012
      severity: 'MEDIUM'
    - name: Immutable container file systems
      description: 'Check that container root file system is immutable'
      id: '1.1'
      mapping:
        scanner: vuln
        checks:
          - id: KSV014
      severity: 'LOW'
    - name: Share containers process namespaces
      description: 'Controls whether containers can share process namespaces'
      id: '1.3'
      mapping:
        scanner: secret
        checks:
          - id: KSV008
      severity: 'HIGH'
   
```

## Logic :
- Reading spec yaml file and identifying scanners types and run only them
- Once scan is completed , running mapping logic to aggregate all resources results by check ID
- Create custom reports result objects with control check and it related scanner check results
- Presenting reports in two formats, summary (table) and granular (JSON) 

## Reports

### Table
