### ISSUE TITLE
helm chart does not work with kubernetes 1.25

### ISSUE THREAD

**Issue by zetaab** [aquasecurity/trivy#2930]
## Description

Unable to use trivy helm chart anymore with Kubernetes 1.25 because the PodSecurityPolicy api is removed

## What did you expect to happen?

I expect that I could use trivy helm chart with kubernetes 1.25

## What happened instead?

```
 % helm upgrade trivy aquasecurity/trivy --install --namespace kapi --values values-trivy.yaml --set image.tag=0.32.0                  
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

values-trivy.yaml

```
trivy:
  cache:
    redis:
      enabled: true
      url: redis://keydb:6379
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
rbac:
  create: false
  pspEnabled: false
```

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```
