### ISSUE TITLE
config scan of k8s manifests false-positive with securityContext.allowPrivilegeEscalation

### ISSUE THREAD

**Issue by tipruzs** [aquasecurity/trivy#3018]
## Description

When running a config scan against kubernetes statefulset yaml i get a false-positive for _securityContext.allowPrivilegeEscalation_. In my use case i describe a statefulset with one container and one initContainer. The container provides the securityContext and the initContainer does not. Trivy reports ksv001 for the container, which is not expected.

## What did you expect to happen?

Trivy reports misconfiguration for the initContainer

## What happened instead?

Trivy reports misconfiguration for container and initContainer

## Output of run with `-debug`:

```
2022-10-13T11:24:45.524+0200    DEBUG   Severities: ["MEDIUM" "HIGH" "CRITICAL"]
2022-10-13T11:24:45.594+0200    DEBUG   cache dir:  /home/******/.cache/trivy
2022-10-13T11:24:45.594+0200    INFO    Misconfiguration scanning is enabled
2022-10-13T11:24:46.035+0200    DEBUG   OS is not detected.
2022-10-13T11:24:46.035+0200    INFO    Detected config files: 1
2022-10-13T11:24:46.035+0200    DEBUG   Scanned config file: manifest.yaml

manifest.yaml (kubernetes)

Tests: 24 (SUCCESSES: 21, FAILURES: 3, EXCEPTIONS: 0)
Failures: 3 (MEDIUM: 2, HIGH: 1, CRITICAL: 0)

MEDIUM: Container 'init' of StatefulSet 'sample' should set 'securityContext.allowPrivilegeEscalation' to false
A program inside the container can elevate its own privileges and run as root, which might give the program control over the container and node.
See https://avd.aquasec.com/misconfig/ksv001

 manifest.yaml:54-67
  54 ┌         - image: init:1.2.3
  55 │           imagePullPolicy: IfNotPresent
  56 │           name: init
  57 │           resources:
  58 │             limits:
  59 │               cpu: 25m
  60 │               memory: 32Mi
  61 │             requests:
  62 └               cpu: 25m
  ..   

MEDIUM: Container 'sample' of StatefulSet 'sample' should set 'securityContext.allowPrivilegeEscalation' to false
A program inside the container can elevate its own privileges and run as root, which might give the program control over the container and node.
See https://avd.aquasec.com/misconfig/ksv001

 manifest.yaml:21-51

  21 ┌         - image: sample:1.2.3
  22 │           imagePullPolicy: IfNotPresent
  23 │           livenessProbe:
  24 │             httpGet:
  25 │               path: /health
  26 │               port: 8080
  27 │             initialDelaySeconds: 60
  28 │             periodSeconds: 60
  29 └             timeoutSeconds: 2
  ..   



HIGH: Container 'init' of StatefulSet 'sample' should set 'securityContext.privileged' to false
Privileged containers share namespaces with the host system and do not offer any security. They should be used exclusively for system containers that require high privileges.
See https://avd.aquasec.com/misconfig/ksv017

 manifest.yaml:54-67

  54 ┌         - image: init:1.2.3
  55 │           imagePullPolicy: IfNotPresent
  56 │           name: init
  57 │           resources:
  58 │             limits:
  59 │               cpu: 25m
  60 │               memory: 32Mi
  61 │             requests:
  62 └               cpu: 25m
  ..   
```

## Output of `trivy -v`:

```
Version: 0.32.1
```

## Additional details (base image name, container registry info...):

As soon as i remove the initContainer from the definition the issue is gone.
Perhaps there are additional checks effected.

manifest.yml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: sample
  name: sample
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample
  serviceName: sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample
    spec:
      automountServiceAccountToken: false
      containers:
        - image: sample:1.2.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 2
          name: sample
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsUser: 1000
      enableServiceLinks: false
      initContainers:
        - image: init:1.2.3
          imagePullPolicy: IfNotPresent
          name: init
          resources:
            limits:
              cpu: 25m
              memory: 32Mi
            requests:
              cpu: 25m
              memory: 32Mi
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      terminationGracePeriodSeconds: 600
```
