### ISSUE TITLE
Trivy operator first start, pulls duplicate docker images

### ISSUE THREAD

**Issue by AlexsJones** [aquasecurity/trivy#3119]
1. MicroK8s 4 node raspberry pi cluster
2. ArgoCD pulling the following

```
{{- if .Values.trivy.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.5.0
    helm:
      values: |
        serviceMonitor:
          enabled: true # has to be false if you do not have Prometheus already installed
        trivy:
          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
```

What you will see is that `trivy-system` is populated by over 10 pods ( I suppose this in relation to workloads it wants to scan?) 
They are all pulling the same image from docker hub so I hit a timeout and they back off with a failure.
![Screenshot 2022-11-02 at 10 00 35](https://user-images.githubusercontent.com/1235925/199461210-44520b2a-2afe-45a0-b4ba-f1e05a3284b4.png)
