### ISSUE TITLE
Add a Markdown format template

### ISSUE THREAD

**Issue by ohmer** [aquasecurity/trivy#3201]
Hi there,

Not exactly a feature request, more of an humble proposal to include a new report formatter.

I am using Trivy in GitHub Actions to scan container images. I wanted to make report easy to read in the context of a PR check. SARIF looked like great way to get there but I do not have [Advanced Security](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security). So I created a report template that generates Markdown compatible HTML to reach my goal. Maybe it could be useful to the community hence this proposal.

Here is how it looks like when added to a [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/):

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1216016/202832009-5b4adc91-6f6e-4682-8dab-43447d63a61b.png">

Note that the CVE link is automatically generated by GitHub which leads to similar references as in the report.

Example of usage:

```yaml
  trivy:
    name: Trivy scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: .
      - run: mkdir oci && tar -C oci -xf ${{ github.sha }}.tar
      - uses: aquasecurity/trivy-action@master
        with:
          input: oci
          format: template
          template: "@trivy/github-markdown.tpl"
          output: trivy.md
          security-checks: vuln
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 1
      - run: cat trivy.md >> $GITHUB_STEP_SUMMARY
        if: always()
```

**Comment by knqyf263** [comment]
Thanks for your proposal. Please let us see how much this feature is needed in the community to decide if we will accept this proposal.

**Comment by michadvorak-cen38289** [comment]
Just stumbled on the exactly same issue, please add this template, thanks!

**Comment by michadvorak-cen38289** [comment]
@ohmer You can actually output directly to step summary, even thou it is missing in the documentation (I'm pretty sure by accident), via `${{ github.step_summary }}`

```yaml
 - uses: aquasecurity/trivy-action@master
    with:
      format: template
      template: "@trivy/github-markdown.tpl"
      output: ${{ github.step_summary }}
```

**Comment by saerosV** [comment]
I think this is a great addition to Trivy, it would greatly benefit people who don't have access to GitHub Advanced Security features.

A [similar feature was already proposed and discussed earlier this year](https://github.com/aquasecurity/trivy-action/issues/110), in the Trivy Action repository, but the maintainers there apparently put it on hold.

@knqyf263

**Comment by tperka-catalogicsoftware** [comment]
Is it implemented now? I would also love to use this

**Comment by saerosV** [comment]
@michadvorak-cen38289 

Were you able to make the following piece of code work, with an existing format or template?

```
- uses: aquasecurity/trivy-action@master
  with:
    format: template
    template: "@trivy/github-markdown.tpl"
    output: ${{ github.step_summary }}
```

I tested it with the markdown template (`"@trivy/github-markdown.tpl"`) and other formats, but all I got in return was the following error:

```
flag error: report flag error: failed to create an output file: open /home/runner/work/_temp/_runner_file_commands/step_summary_id-number: no such file or directory
```

**Comment by dstrates** [comment]
@michadvorak-cen38289 @saerosV 

I'm receiving the same error in a GitHub hosted runner. Any tips?

I assumed the `github-markdown.tpl` needs to exist in the GitHub workspace context and that we prefix this with @ (i.e. `"@github-markdown.tpl"`) as per the [documentation examples](https://aquasecurity.github.io/trivy/v0.37/docs/vulnerability/examples/report/).

**Comment by saerosV** [comment]
Hi @dstrates.

Correct, the template needs to exist.

I tested using the HTML template: 

```YAML
format: template
template: "@/contrib/html.tpl"
output: ${{ github.step_summary }}
```
and the `table` format, but still got the same results.

**Comment by dstrates** [comment]
FWIW ohmer's original example works fine with the separate step:

```
      - uses: aquasecurity/trivy-action@master
        with:
          input: oci
          format: template
          template: "@trivy/github-markdown.tpl"
          output: trivy.md
          security-checks: vuln
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 1
  - run: cat trivy.md >> $GITHUB_STEP_SUMMARY
        if: always()
```

**Comment by saerosV** [comment]
This issue can now be closed since #3202 (related PR) was also closed.

@itaysk.

**Comment by AshwinSarimin** [comment]
I have solved this by creating the markdown.tpl in the repository, with the content provided by ohmer (https://github.com/aquasecurity/trivy/pull/3202/files), and with the following code I am able to the results in the job summary:

`- name: Run Trivy config scanner - High,Critical
      uses: aquasecurity/trivy-action@master
      with:
        scan-ref: ${{ inputs.moduleFolderPath }}
        scan-type: 'config'
        hide-progress: false
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        format: template
        template: "@/github/workspace/software/trivy/templates/markdown.tpl"
        output: trivy-high-critical.md
`

Because the Trivy scanner runs inside a docker instance, it mounts the checked out repository as a volume inside that container. The volume is mounted as:
`-v "/home/runner/work/REPOSITORY":"/github/workspace"`

So to be able the retrieve the markdown template from the repository I have to use '@/github/workspace/' and then the template file location (software/trivy/templates/markdown.tpl)

Not my preferred way of doing this, but it works.

**Comment by itaysk** [comment]
trivy never had a build it markdown template https://github.com/aquasecurity/trivy/pull/3202#issuecomment-1500497668

**Comment by itaysk** [comment]
https://github.blog/2022-07-01-extend-your-dependency-information-in-the-github-dependency-graph-with-new-github-actions/

**Comment by itaysk** [comment]
yes github format was created only for github's dependencies tab integration

**Comment by VegardEikenes** [comment]
This feature is still needed, especially when using reusable workflows. This should be easy to implement, as the template is already written.

**Comment by mac2000** [comment]
In case it will help someone, there is a way to prepare customized tables like so:

lets pretend we have some kind of action like this one:

```yml
name: demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/setup-trivy@v0.2.2
      - run: docker build -t demo .
      
      # and here we are running trivy scan for image built in previous step
      # note that output format is set to json, and results are saved to trivy.json file
      - run: trivy image demo --no-progress --security-checks vuln --exit-code 0 --ignore-unfixed --severity CRITICAL,HIGH --format json --output trivy.json
      
      # POI: extract wanted info from json into html table
      - shell: pwsh
        run: Get-Content trivy.json | ConvertFrom-Json | Select-Object -ExpandProperty Results | Select-Object -ExpandProperty Vulnerabilities | Select-Object Severity, PkgName, InstalledVersion, FixedVersion, Status, Title | ConvertTo-Html -Fragment | Out-File trivy.html

      - run: cat trivy.html >> $GITHUB_STEP_SUMMARY
```

results will be something like:

<img width="1321" alt="Image" src="https://github.com/user-attachments/assets/6825cabc-e015-4ec0-83eb-ebc6d9791bae" />


<details>
<summary>how it works</summary>

- note that we are using powershell (pwsh) instead of bash (default), it is already preinstalled in github agents, so will work out of the box
- `Get-Content trivy.json` - aka `cat trivy.json`
- ` | ConvertFrom-Json` - aka `| jq`
- followup `Select-Object xxxx` - are chain of commands to extract wanted data from given json
- ` | ConvertTo-Html -Fragment` - will produce html table from given input
- ` | Out-File trivy.html` - same as `| tee trivy.html`

</details>
