### ISSUE TITLE
Doc Indentation - Installing the Trivy-Operator through GitOps

### ISSUE THREAD

**Issue by michaelsatish** [aquasecurity/trivy#3266]
## Description

The example provided under the "FluxCD" section has an incorrect indentation. 
The "namespace" under the "SourceRef". 

https://github.com/aquasecurity/trivy/blob/main/docs/tutorials/kubernetes/gitops.md#fluxcd

## How it looks

```yaml
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
				namespace: flux-system
      version: 0.0.5
  interval: 60m
```

## How it should look

```yaml
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: flux-system
      version: 0.0.5
  interval: 60m
```
