### ISSUE TITLE
Doesn't detect all config files particularly CloudFormation templates

### ISSUE THREAD

**Issue by aigerim-zhalgasbekova-paf** [aquasecurity/trivy#3418]
## Description

Trivy doesn't detect all CloudFormation files existing in a directory when running the following command:
```
% trivy config ./deploy
```

## What did you expect to happen?
Trivy should detect 4 .yaml files
```bash
├── deploy
    ├── cf-apigw-lambdas-stack.yaml
    ├── cf-monitoring.yaml
    ├── cf-s3-trust-store.yaml
    ├── cf-s3.yaml
```

## What happened instead?
It detects 0 instead (in some projects where I tested this command it finds one or more files but not all)

## Output of run with `-debug`:
```
% trivy config --debug ./deploy
2023-01-12T10:53:27.094+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-01-12T10:53:27.135+0200	DEBUG	cache dir:  /Users/aigzha/Library/Caches/trivy
2023-01-12T10:53:27.135+0200	INFO	Misconfiguration scanning is enabled
2023-01-12T10:53:27.135+0200	DEBUG	Walk the file tree rooted at 'deploy' in parallel
2023-01-12T10:53:27.425+0200	DEBUG	OS is not detected.
2023-01-12T10:53:27.425+0200	INFO	Detected config files: 0
```

## Output of `trivy -v`:

```
% trivy -v
Version: 0.36.1
```

**Comment by aigerim-zhalgasbekova-paf** [comment]
I've also tried the command with `--file-patterns` but it doesn't work either.
```
% trivy conf --file-patterns "yaml:cf-monitoring" --debug ./deploy
2023-01-12T11:08:36.318+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-01-12T11:08:36.361+0200	DEBUG	cache dir:  /Users/aigzha/Library/Caches/trivy
2023-01-12T11:08:36.361+0200	INFO	Misconfiguration scanning is enabled
2023-01-12T11:08:36.361+0200	DEBUG	Walk the file tree rooted at 'deploy' in parallel
2023-01-12T11:08:36.658+0200	DEBUG	OS is not detected.
2023-01-12T11:08:36.658+0200	INFO	Detected config files: 0
```

**Comment by itaysk** [comment]
can you please show a sample for one of the files? CF files are detected as either yaml/json files with the abstract structure of: an object with a "Resources" key which contains an object:
https://github.com/aquasecurity/defsec/blob/master/pkg/detection/detect.go#L125

**Comment by aigerim-zhalgasbekova-paf** [comment]
The following is a sample for all our CF templates with .yaml extension:
```
WSTemplateFormatVersion: "2010-09-09"
Description: Example CloudFormation template, please provide correct description!

Parameters:

### Setup the input parameters of template here ###

Conditions:

### Setup the conditions here ###

Resources:
### Resources that will be created by this template ###

Outputs:
### Setup the values that need to be exported to other CloudFormation stacks here ###
```

**Comment by aigerim-zhalgasbekova-paf** [comment]
I found that Trivy doesn't detect CF templates that have the following condition:
```
Conditions:
  ## This cryptic syntax sets SuffixResources = true if EnvName != ""
  SuffixResources: !Not [!Equals [!Ref EnvName, ""]]
```
Do you have any idea why it happens?

**Comment by itaysk** [comment]
Does this YAML pass validation, and does it parse the way you intend it to? specifically, this value is error prone: `!Not [!Equals [!Ref EnvName, ""]]`. can you try to single quote it? `'!Not [!Equals [!Ref EnvName, ""]]'`

**Comment by aigerim-zhalgasbekova-paf** [comment]
The condition works for all our CF stacks. cfn-lint also doesn't complain about it. When I single quote it like you suggest, cfn-lint throws `Condition SuffixResources has invalid property`.

**Comment by aigerim-zhalgasbekova-paf** [comment]
We follow the conditions syntax -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-not

**Comment by aigerim-zhalgasbekova-paf** [comment]
@itaysk I found out that trivy can't detect the templates with the condition used in `If` clause like here ->
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: some description
Parameters:
  ServiceName:
    Type: String
    Description: The service name
  EnvName:
    Type: String
    Description: Optional environment name to prefix all resources with
    Default: ""

Conditions:
  ## This cryptic syntax sets SuffixResources = true if EnvName != ""
  SuffixResources: !Not [!Equals [!Ref EnvName, ""]]

Resources:
  ErrorTimedOutMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "?ERROR ?error ?Error ?\"timed out\"" # If log contains one of these error words or timed out
      LogGroupName:
        !If [
          SuffixResources,
          !Sub "/aws/lambda/${ServiceName}-${EnvName}",
          !Sub "/aws/lambda/${ServiceName}",
        ]
      MetricTransformations:
        - MetricName: !Sub "${ServiceName}-ErrorLogCount"
          MetricNamespace: market-LogMetrics
          MetricValue: 1
          DefaultValue: 0
```
When I use the condition directly in the `!If` like:
```
      !If [
          !Not [!Equals [!Ref EnvName, ""]],
          !Sub "/aws/lambda/${ServiceName}-${EnvName}",
          !Sub "/aws/lambda/${ServiceName}",
        ]
```
Trivy detects the template.
