### ISSUE TITLE
support  docker multi credential env varaible

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3629]
It is require to have support for docker multi credential values comma separated
example 
export TRIVY_USERNAME=user1,user2,user3
export TRIVY_PASSWORD=pass1,pass2,pass3

use case :
K8s Pod with two containers in same registry but uses different secret :
```
automountServiceAccountToken: True
      imagePullSecrets:
        - name: "registry-secret-1"
        - name: "registry-secret-2"
      containers:
        - name: "container-1"
          image: "git-images.registry.de/path/to/first/image/images/image-1:tag"
        - name: "container-2"
          image: "git-images.registry.de/path/to/second/image/images/image-2:tag"
``` 
this is how [k8s pull image works](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_image.go#L61)
