### ISSUE TITLE
Trivy@1 Azure DevOps task - how to form image input

### ISSUE THREAD

**Issue by guywood13** [aquasecurity/trivy#3762]
Trying to do a trivy scan of an image in an Azure Container Registry (ACR).  Docker login is working fine, I'm just not sure I'm getting the image input string right?

I've gone for this format: login server url / ACR Name / image name : image tag

Is that right?  Can't find any other examples online other than https://marketplace.visualstudio.com/items?itemName=AquaSecurityOfficial.trivy-official&ssr=false#overview.

**YAML**
```
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: My-ACR-Dev
- task: trivy@1
  inputs:
    image: myacr.azurecr.io/MyAcr/myimage:1.0.162
```

**Error**
`2023-03-03T11:47:25.587Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: failed to parse the image name: could not parse reference: myacr.azurecr.io/***/myimage:1.0.162`
