### ISSUE TITLE
Trivy server -c config file does not take cache-dir option

### ISSUE THREAD

**Issue by senemamourr** [aquasecurity/trivy#3872]
We use trivy on server mode and we need to configure it with a config file like
trivy server -c "pathtoconfig/config.yml"
but unfortunaly it does not take the cache-dir option defined like this:
cache-dir: /pathtocachedir
server:
  listen: 0.0.0.0:8080

can you help please ?

**Comment by DmitriyLewen** [comment]
Hello @senemamourr 
Thanks for your report!

Docs contain mistake.
Use next config:
```yaml
cache:
  dir: /pathtocachedir
server:
  listen: 0.0.0.0:8080
```

We will change docs soon.

Regards, Dmitriy
