### ISSUE TITLE
false positive - python-setuptools

### ISSUE THREAD

**Issue by faust64** [aquasecurity/trivy#4067]
## Description

A while ago, I pinged RedHat support, regarding some python-setuptools vunerability spotted by Trivy.
Since then, support got back to me and confirmed the fix was now avaialable.

Yet trivy keeps reporting about that vulnerability:

```
class: lang-pkgs
type; python-pkg
vulnerability:
  ID: CVE-2022-40897
  PkgName: setuptools
  PkgPath: /opt/app-root/kube/python3.9/site-packages/setuptools-53.0.0.dist-info/METADATA
  InstalledVersion: 53.0.0
  FixedVersion: 65.5.1
  ...
  Descripition: Python Packaging Authority (PyPA_ setuptools before 65.5.1 allows remote attackers to cause a denial of service .......
```

For the record, RedHat advertises ( access.redhat.com/errata/RHSA-2023:0952 ) that the fix ships in python3-setuptools-53.0.0-10.el9_11.noarch.rpm.

I think this may be a false positive. Given Trivy seems certain the only fix would be to upgrade to 65.5.1 ...
Am I doing it wrong? Should I wipe the cache of my trivy container and try again (db looks up to date/just upgraded yesterday, in doubt)?

Those scans have been marked as failing for over a month, since RedHat came through and told me they shipped their own fix.

## What did you expect to happen?

Building an image from ubi9/python39. With few dependencies (kopf/kubernetes libs). I would expect my scans to find 0 vulnerablities.
According to RH container registry, there shouldn't be any known vulnerability here: https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?tag=1-114.1681379027&push_date=1681409110000

## What happened instead?

Scan keeps reporting 1 vulnerability. RedHat insists it's no longer vulnerable.
Who should I trust?

## Output of run with `-debug`:

can't share this / don't have access to GitHub from the workstation I use operating my customer's clusters.
details about vulnerability shared above.
still persists as of today, using redhat's latest image (released yesterday evening)

## Output of `trivy -v`:

(from my trivy server / scans would be running on clients with no persistent volume attached)

```
Version: 0.39.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-04-14 06:09:41:... UTC
  NextUpdate: 2023-04-14 12:09:41... UTC
  DownloadedAt: 2023-04-14 06:39:27... UTC
```

## Additional details (base image name, container registry info...):

N/A
