### ISSUE TITLE
Trivy can't find image in Docker in Docker (DinD) configuration

### ISSUE THREAD

**Issue by be-lka** [aquasecurity/trivy#4078]
## Description
Team of developers have a repository in GitLab that configures Docker in Docker environment like the following:
```yaml
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
```
Trivy then proceeds to look for the image in the specified `DOCKER_HOST` address and stalls while doing it:
```bash
2023-04-05T14:48:48.956Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (registry-address.com.br/image:2865): error during connect: Get "http://docker:2375/v1.24/images/registry-address.com.br/image:2865/json": dial tcp: lookup docker on 100.64.0.10:53: no such host
```

## What did you expect to happen?
Expected Trivy to find the image and scan it.

## What happened instead?
Trivy cannot find the image in the specified DOCKER_HOST and I can't find in the docs any way to specify a different DOCKER_HOST for Trivy to find the registry.

## Output of `trivy -v`:

```
Version: 0.38.3
```
