### ISSUE TITLE
fix(misconf): evaluate the value for a cloudformation property when comparing

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#4832]
If the resource property is the value returned by the function, then this value is not taken into account.

For example, for the following configuration:
```yaml
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnableVersioning:
    Type: String
    Default: "TRUE"
    Description: Input "TRUE" when enabling versioning

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status:
          !If [!Equals [!Ref EnableVersioning, "TRUE"], Enabled, Suspended]
```

I get the output:
```
...
AVD-AWS-0090 aws-s3-enable-versioning test.yaml:15
...
```

which is incorrect, because versioning is enabled.
