### ISSUE TITLE
Allow providing private registry credentials via files for k8s & docker secrets

### ISSUE THREAD

**Issue by bitsofinfo** [aquasecurity/trivy#523]
Allow providing private registry credentials via files. Looks like currently you have to do it via ENV vars. Please add an option to specify locations of files that contain each of these values

TRIVY_USERNAME_FILE
TRIVY_PASSWORD_FILE
TRIVY_AUTH_URL_FILE

If this is supported, then people can just map these to mounted kubernetes or docker secrets

**Comment by Johannestegner** [comment]
Wouldn't the ability to use a standard docker configuration alt the credentials store that docker uses be a preferable idea? Locally, it would make your client just work out of the box, while in remote mode, it would only require a single secret with the config file or even a pass container with the credentials in.

Either way, I think that there are more than me who uses multiple registries, hence being able to at the least put multiple credentials, from start, in the files above would be a good thing!

**Comment by bitsofinfo** [comment]
great! still, would like this option, already have these creds in k8s secrets and need to access them

**Comment by bitsofinfo** [comment]
for anyone else, here is a workaround 

```
    - name: trivy-scan
      image: docker.io/aquasec/trivy:0.9.1
      env:
        - name: "TRIVY_AUTH_URL"
          value: "https://myprivatereg"
      command:
        - /bin/ash
      args:
        - -c
        - |
          TRIVY_USERNAME=$(cat /mounted-k8-secret/username) \
          TRIVY_PASSWORD=$(cat /mounted-k8-secret/password) \
          /usr/local/bin/trivy \
          client \
          --remote http://cicd-trivy-server.tekton-pipelines:80 \
          --token xyz \
          --exit-code 0 \
          --severity MEDIUM,HIGH,CRITICAL \
          myprivatereg/abc/$(inputs.params.appName):$(inputs.params.appTag) 
```

**Comment by jonaz** [comment]
Why not just? 
```
          env:
            - name: "TRIVY_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: username
            - name: "TRIVY_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: password
```
