### ISSUE TITLE
feat(rust): Support workspace.members parsing for Cargo.toml analysis

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#5283]
### Description
Support workspace in `Cargo.toml`.

```toml
[workspace.package]
version = "2.8.1"

[workspace]
members = ["casr", "libcasr"]
```

It doesn't have any dependencies in workspace, all dependencies are located in members.
