### ISSUE TITLE
bug(cloudformation): Trivy sometimes fails to recognise string interpretations of Boolean values

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#5802]
Successfully:
```yaml
Resources:
  GoodExample:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 100
      Encrypted: "true" # <---
      KmsKeyId: "alias/volumeEncrypt"
    DeletionPolicy: Snapshot
```

Didn't recognise it:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-79fd7eee"
      KeyName: "testkey"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
          Encrypted: "true" # <---
```

```bash
HIGH: Root block device is not encrypted.
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Block devices should be encrypted to ensure sensitive data is held securely at rest.

See https://avd.aquasec.com/misconfig/avd-aws-0131
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 test.yaml:15
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  15 [           Encrypted: "true" # <---
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Ref:
- https://www.awholenother.com/2020/06/20/boolean-parameters-in-cloudformation.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
