### ISSUE TITLE
Add Azure DevOps Support

### ISSUE THREAD

**Issue by eddyv73** [aquasecurity/trivy#593]
Many organizations uses Azure DevOps, is good idea create a Azure DevOps marketplace item to add in the pipelines.

[https://marketplace.visualstudio.com/azuredevops](url)

**Comment by cfguimaraes** [comment]
I'm using Azure DevOps and have spent about 30 hours trying to integrate Trivy in pipeline.
Using Amazon ECR as registry I've success in the following way:

1. Get artifact to build container image
2. Use docker command to build image
3. Use **AWS ECR** step to push image
4. Use **AWS Shell Script** step to autenticate in AWS
4.1. In script run inlined:  
          `docker run --rm -v ~/.docker/config.json:/root/.docker/config.json -v /tmp:/root/.cache/ aquasec/trivy image <id>.dkr.ecr.us-east-1.amazonaws.com/<image>:<tag>`
! Important to note the parameter `-v ~/.docker/config.json:/root/.docker/config.json`

**Comment by cfguimaraes** [comment]
The trick is the authentication (for private registry) and more can be found in #377

**Comment by eddyv73** [comment]
Thanks, but for example in my organization all CR stay on Azure, this option is good idea but no for all organizations.

**Comment by cfguimaraes** [comment]
For those who use Azure and havn't integrated yet follow this [link](https://lgulliver.github.io/container-security-scanning-with-trivy-in-azure-devops/).
Is easiest than my steps above.

**Comment by cfguimaraes** [comment]
@eddyv73 have you already integrated?
If yes, post your findings here, so anyone can benefit until Aqua deploy a official way.

**Comment by eddyv73** [comment]
Nice, I found similar solution.

> For those who use Azure and havn't integrated yet follow this [link](https://lgulliver.github.io/container-security-scanning-with-trivy-in-azure-devops/).
> Is easiest than my steps above.

**Comment by Eneuman** [comment]
I found a way, although it uses undocumented "features" and is probobly not supported  :)

First part of script just downloads and installs trivy. 

When building the image, you need to add the following argument `arguments: '-t local/trivy'` to the task.
This will add a a extra local repository. You will need this later when saving the image to disk.

We can't use the repository that the task adds, since MS decided to add "***" characters infront of it so no other docker commands should work, guess they did think of this trick.

In the next task "Save docker image", we use the fact that the "Docker@2" task can actually take any docker command and run it.

We save the created docker image as a tar file on disk, and after that calls trivy to scan it, using the `--input` argument and points it to our local .tar file.

```
    - script: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v${{ parameters.trivyVersion }}/trivy_${{ parameters.trivyVersion }}_Linux-64bit.deb
        sudo dpkg -i trivy_${{ parameters.trivyVersion }}_Linux-64bit.deb
        trivy -v
      displayName: 'Download and install Trivy'

    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: ${{ parameters.containerRegistry }}
        repository: ${{ parameters.imageRepository }}
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
        arguments: '-t local/trivy'

    - task: Docker@2
      displayName: Save docker image
      inputs:
        command: 'save'
        arguments: '-o $(Build.ArtifactStagingDirectory)/imagetoscan.tar local/trivy'

    - task: CmdLine@2
      displayName: "Run trivy scan"
      inputs:
        script: |
          trivy image --input $(Build.ArtifactStagingDirectory)/imagetoscan.tar         

```

There ya go.
