### ISSUE TITLE
Unable to load images built by Kaniko via gitlab

### ISSUE THREAD

**Issue by imdhruva** [aquasecurity/trivy#601]
I understand that `kaniko` images are [officially supported](https://github.com/aquasecurity/trivy/pull/171) however my GitLab CI pipeline throws up following err:
```bash
2020-08-17T06:34:22.005Z	INFO	Need to update DB
2020-08-17T06:34:22.005Z	INFO	Downloading DB...
2020-08-17T06:34:23.904Z	FATAL	unable to initialize a scanner: unable to initialize the archive scanner: 2 errors occurred:
	* unable to open image.tar as a Docker image: unable to open the file: open image.tar: no such file or directory
	* unable to open image.tar as an OCI Image: stat image.tar/index.json: no such file or directory
```
output of command `tar -tvzf image.tar`:
```bash
-rw-r--r-- 0/0          510326 1970-01-01 00:00 3b2e482019db2dc355dda150025ed5cd8261a282b2e3afa17601603c3b2bc4f6.tar.gz
.
.<redacted>
.
-rw-r--r-- 0/0        23050001 1970-01-01 00:00 62e715b3d884e75567894221263814a7bcb1f13d13d1a2a31f14d2e318673d61.tar.gz
-rw-r--r-- 0/0            1435 1970-01-01 00:00 manifest.json
```
`gitlab-ci.yaml`:
```yaml
variables:
  CI_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - image.tar
    - cache/image
stages:
  - build
  - test
  # - deploy-int
  # - deploy-qa

build image:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.24.0
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache-dir cache/image --tarPath image.tar --destination $CI_IMAGE
  except:
    - schedules
container scanning:
  stage: test
  image:
    name: aquasec/trivy:latest
  variables:
    GIT_STRATEGY: none
    TRIVY_NO_PROGRESS: "true"
  allow_failure: true
  script:
    # Build report
    - trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/gitlab.tpl" -o gl-container-scanning-report.json --input image.tar
    # Print report
    - trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --severity HIGH --input image.tar
    # Fail on high and critical vulnerabilities
    - trivy --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress --input image.tar
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  dependencies: []
  only:
    refs:
      - branches
  except:
    - schedules

```
