### ISSUE TITLE
Add support to ignore by PURL

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#6119]
## Description
Adding PURL support in `.trivyignore.yaml`.

```
vulnerabilities:
  - id: CVE-2022-40897
    packages:
      - pkg:deb/debian/curl@7.50.3-1
```

### Discussed in https://github.com/aquasecurity/trivy/discussions/6118
