### ISSUE TITLE
Private registry integration - AWS ECR

### ISSUE THREAD

**Issue by scapotondo** [aquasecurity/trivy#7161]
### Discussed in https://github.com/aquasecurity/trivy/discussions/7046

<div type='discussions-op-text'>

<sup>Originally posted by **scapotondo** June 27, 2024</sup>
### Question

Hey folks,

I'm trying to create a pipeline stage using GitlabCI where I analyze a previously uploaded docker image stored in ECR and I'm facing issues. Let me provide more information:

Error:
`FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "<ecr-docker-image-url>" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (<ecr-docker-image-url>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* containerd error: containerd socket not found: /run/containerd/containerd.sock
	* podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* remote error: GET : unexpected status code 401 Unauthorized: Not Authorized`

Docker image used: https://hub.docker.com/r/bitnami/trivy/ version [0.52.2](https://hub.docker.com/layers/bitnami/trivy/0.52.2/images/sha256-b5f33ab8a75054e3233d93412e6660025bdb5c5eefc40dce42133722f24f5eb9?context=explore)

I've tried stuff following documentation and taking a look at the proyect on my local machine but it haven't been enough. I'll share the GitlabCI job that I'm using

---
```yaml
.image-scan:
  stage: image-scan
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    YOUR_USERNAME: "<aws-user>"
    YOUR_PASSWORD: "<aws-pwd>"
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    IMAGE: ${IMAGE_REPO}:${IMAGE_TAG}
  script:
    - trivy --version
    - TRIVY_PASSWORD=${YOUR_PASSWORD} trivy image --username ${YOUR_USERNAME} ${IMAGE}
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json
  needs:
    - entry
    - build
```

`IMAGE_REPO` var points to the ecr repository and `IMAGE_TAG` to the tag for the specific project.

We're using pod identity to authenticate with aws

Documentation that I've used:
- https://aquasecurity.github.io/trivy/v0.52/docs/references/troubleshooting/#container-registry
- https://aquasecurity.github.io/trivy/v0.52/docs/advanced/private-registries/ecr/

Let me know if you need more information from my side

### Target

AWS

### Scanner

Misconfiguration

### Output Format

None

### Mode

Client/Server

### Operating System

I'm using trivy inside a docker container

### Version

```bash
0.52.2
```
</div>
