### ISSUE TITLE
bug(k8s): Image scanned from "metadata:annotations:kubectl.kubernetes.io/last-applied-configuration" instead of "spec"

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#7573]
## Description
since #4786  (https://github.com/aquasecurity/trivy-kubernetes/pull/189) Trivy scan last applied configuration instead of actual Resource state.

## Reason
For scans Trivy prefers info from an annotation. so if a customer mixes imperative and declarative styles, the result is a bit confusing.

https://github.com/aquasecurity/trivy-kubernetes/blob/b070991579cacd7634052dee2e250350d6e493e8/pkg/trivyk8s/trivyk8s.go#L208-L214

**Note**: the issue will be happened only if a resource is created from `kubectl apply`. 

## Solution
We can try to receive a version info more flexible way

## Reproduction Steps
1. Create a deployment:
```sh
$ kubectl apply -f nginx-deployment.yaml
```
<details>
<summary>/nginx-deployment</summary>
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    web: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80
```
</details>

2. update an image manually:
```sh
$ kubectl set image deployment.apps/nginx-deployment nginx=nginx:1.15.0
```

3. Result:
```sh
$ kubectl get deployment.apps/nginx-deployment -o yaml
```
<details>
<summary>nginx-deployment details</summary>
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx","web":"my-app"},"name":"nginx-deployment","namespace":"7551"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.1","name":"nginx","ports":[{"containerPort":80}]}]}}}}
  labels:
    app: nginx
    web: my-app
 pec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        ports:
        - containerPort: 80
...
```
</details>

4. Trivy will scan `nginx:1.14.1` instead of `nginx:1.15.0", that actually runs in a cluster.

### Discussed in https://github.com/aquasecurity/trivy/discussions/7551
