### ISSUE TITLE
fix(misconf): handle null properties in CloudFormation templates

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy#7809]
Template analysis stops if there is at least one null property in the template. Trivy must handle such properties correctly.

Template:
```yaml

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TestBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
```

Output:
```bash
2024-10-29T11:18:20+06:00       ERROR   [cloudformation parser] Error parsing file      file_path="main.yaml" err="panic during parse: runtime error: invalid memory address or nil pointer dereference"
```
