### ISSUE TITLE
bug(k8s): inconsistent results from summary and all report on k8s workload

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#7937]
## Description
There are cases when `summary` report doesn't contain information about vulnerabilities.

## Reason
For consolidated report Trivy looks for vulns and secrets only in the first result.
The second and next results are skipped now.

https://github.com/aquasecurity/trivy/blob/main/pkg/k8s/report/report.go#L282-L283
## Reproduction steps:

```sh
#!/bin/sh
kind delete cluster && kind create cluster
kubectl cluster-info
kubectl wait --for=condition=Ready nodes --all --timeout=300s

kubectl create namespace test
kubectl create -f pod.yaml

trivy k8s --report summary --include-namespaces test
```
`pod.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: postgres-pod
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine3.19
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "admin"
    - name: POSTGRES_PASSWORD
      value: "password"
    - name: POSTGRES_DB
      value: "exampledb"
```
