### ISSUE TITLE
JUnit template isn't compatible with AWS CodeBuild reports

### ISSUE THREAD

**Issue by ga-paul-t** [aquasecurity/trivy#902]
## Description

Having configured an AWS CodeBuild project to perform a scan and capture the output, the AWS CodeBuild project fails due to the report syntax being invalid.

This is a fragment of the buildspec used:

```
version: 0.2
phases:
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/junit.tpl" -o trivy-report.xml $REPOSITORY_URI:$TAG_NAME
      - trivy --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL $REPOSITORY_URI:$TAG_NAME
      - docker push $REPOSITORY_URI:$TAG_NAME
reports:
  trivy:
    files:
      - trivy-report.xml
    file-format: JUNITXML
```

## What did you expect to happen?

The formatted JUnit report to be captured by AWS CodeBuild and made available for inspection in the AWS Console

## What happened instead?

The CodeBuild project fails to capture the report due to the report being invalid. The following error is reported:

```
Error in UPLOAD_ARTIFACTS phase: [trivy: [error processing report: [InvalidInputException: Test summary: status count cannot be negative]]]
```

## Additional details:

It is a fairly straight forward issue to fix. The number of tests within the testsuite just needs to match the number of errors.
